incmap	MACRO
	incfile	maps\\\1.asm
	ENDM

	mapdef	mapp	; player's map address

	INCMAP	map1_6a
	INCMAP	map1_6b

	INCMAP	map2_6a
;	INCMAP	map2_6b
;	INCMAP	map2_6c
;	INCMAP	map2_6d

	INCMAP	map4_1
	INCMAP	map4_2

	INCMAP	map4_4
	INCMAP	map4_5
	
	INCMAP	level4_1
	INCMAP	level4_2
	INCMAP	level4_3
	INCMAP	level4_4
	INCMAP	level4_5
	INCMAP	level_ct
	
	INCMAP	level7_1
	INCMAP	level7_2
	INCMAP	level7_3
	INCMAP	level7_4
	INCMAP	level7_5