;6-4
	message2yellow	frog3,<go through the p-pine trees!>,other		;(1)			part 1
	message2yellow	falcon3,<think you can fly between the trees, fox?>,other		;(2)
	message2yellow	rabbit3,<don't try to fly between those trees, fox!>,other		;(3)

	message2yellow	frog3,<the wind feels s-s-stronger, ribbit!>,other		;(4)		part 2
	message2yellow	falcon3,<is anyone else getting that feeling?>,other		;(5)
	message2yellow	rabbit3,<i can feel the electricity in the air!>,other		;(6)	

;6-5
	message2blue	frog3,<don't fly too l-l-low, you'll hit rocks!>,other		;(7)			part 1
	message2blue	falcon3,<these mountains are so strange###>,other		;(8)
	message2blue	rabbit3,<now's not the time for sightseeing, fox!>,other		;(9)

	message2red	frog3,<there's t-t-too many of them!>,other		;(10)		part 2
	message2red	falcon3,<i always love some target practice!>,other		;(11)
	message2red	rabbit3,<don't go showing off now, stay focused!>,other		;(12)	

;6-6
	message2yellow	frog3,<this is it, ribbit! let's g-g-go!>,other		;(13)			part 1
	message2yellow	falcon3,<time to collect that paycheck, lets go!>,other		;(14)
	message2yellow	rabbit3,<this is our final job, rock and roll!>,other		;(15)

	message2red	frog3,<i'm g-g-getting some high energy readings!>,other		;(16)		part 2
	message2red	falcon3,<whatever is up ahead, its really strong!>,other		;(17)
	message2red	rabbit3,<we'll have to be tactical ahead, fox!>,other		;(18)	

;7-1
	message2blue	frog3,<come on fox! i've been p-p-practicing!>,other		;(19)			part 1
	message2blue	falcon3,<i hope we find a real challenge this time!>,other		;(20)
	message2blue	rabbit3,<alright fox, here we go!>,other		;(21)

	message2yellow	frog3,<i've n-n-never seen corneria like this!>,other		;(22)		part 2
	message2yellow	falcon3,<this planet sure is full of life###>,other		;(23)
	message2yellow	rabbit3,<stay focused, somethings up ahead!>,other		;(24)	

;7-2
	message2yellow	frog3,<its really d-d-dry here, ribbit!>,other		;(25)			part 1
	message2yellow	falcon3,<i wonder what we'll find around here#>,other		;(26)
	message2yellow	rabbit3,<i'm just starting to warm up!>,other		;(27)

	message2red	frog3,<d-d-did you hear that noise ahead?>,other		;(28)		part 2
	message2red	falcon3,<hey, are we heading the right way?>,other		;(29)
	message2red	rabbit3,<my radar is all jammed up!>,other		;(30)	

;7-3
	message2blue	frog3,<ahh! it's too c-c-cold!>,other		;(31)			part 1
	message2blue	falcon3,<my feathers are frozen# argh!>,other		;(32)
	message2blue	rabbit3,<i hope our ships hold up in this ice!>,other		;(33)

	message2red	frog3,<i feel s-s-something warm ahead!>,other		;(34)		part 2
	message2red	falcon3,<hey, my feathers freed up!>,other		;(35)
	message2red	rabbit3,<the heat is off the charts ahead!>,other		;(36)	

;7-4
	message2blue	frog3,<that cloud looks like a f-f-frog!>,other		;(37)			part 1
	message2blue	falcon3,<keep your head out of the clouds!>,other		;(38)
	message2blue	rabbit3,<oh my, that is really bright!>,other		;(39)

	message2blue	frog3,<that cloud looks like you, fox!>,other		;(40)		part 2
	message2blue	falcon3,<excuse me, just floating by###>,other		;(41)
	message2red	rabbit3,<my radar is detecting something!>,other		;(42)	

;7-5
	message2yellow	frog3,<let's go! i g-g-got your back!>,other		;(43)			part 1
	message2yellow	falcon3,<lets finish this and get paid!>,other		;(44)
	message2yellow	rabbit3,<i can't wait to retire###>,other		;(45)

	message2blue	frog3,<i hope t-t-this is the end###>,other		;(46)		part 2
	message2blue	falcon3,<its vacation time after this!>,other		;(47)
	message2blue	rabbit3,<this is it! one last job!>,other		;(48)	

;6-2
	messagered	frog3,<things sure are hectic, ribbit!>,other		;(49)
	messagered	falcon3,<i'm glad i replaced my wipers!>,other		;(50)			part 2
	messagered	rabbit3,<i'm seeing something up ahead###>,other		;(51)	

;comet
	messagered	anyone3,<fox, w-w-where are you?? we need backup!>,other	;52
	messagered	anyone3,<hey! i got your signal but i can't see you!>,other	;53
	messagered	anyone3,<fox, we finished the core, where are you?>,other	;54

;comet	2
	messagered	anyone3,<i s-s-see you on our radar! on the way, fox!>,other	;55
	messagered	anyone3,<fox, don't worry about us, we can handle this#>,other	;56
	messagered	anyone3,<we have your position# follow our beacon!>,other	;57

; Yoshi boss text
; NEW
	messagered	anyone3,<gee# it's the famous star fox!>,other	;58
	messagered	yoshi3,<this time, i'm going to handle things#>,other	;59
	messagered	yoshi3,<no more being a sidekick for me#>,other	;60
	messagered	yoshi3,<i bet you taste delicious!>,other	;61

;6-1
	messagered	frog3,<well, this isn't t-t-too bad so far###>,other		;(62)
	messagered	falcon3,<so where's the challenge here?>,other		;(63)			part 2
	messagered	rabbit3,<don't get too comfortable###>,other		;(64)
;6-2
	messageyellow	frog3,<now this is my kind of place!>,other		;(65)
	messageyellow	falcon3,<i better not get my feathers wet!>,other		;(66)			part 1
	messageyellow	rabbit3,<remember, our ships can't go under!>,other		;(67)

;--------intro
; NEW
	messageblue	anyone3,<you may think the galaxy is safe###>,other	;68
	messageblue	anyone3,<but you've only just scratched the surface!>,other	;69
	messageblue	luigi3,<explore the cosmos all you like###>,other	;70
	messageblue	mario3,<###but you'll never beat us!>,other	;71
; Fixed that typo. 9/28/22
; My goal with rewriting this block of text is to make it about exploration, as that's the hack's theme! (Or I think it should be!)
; This project is about all of us exploring the potential of adding new models, music, sprites, and story to the codebase,
; and also about playing with it and having a lot of fun learning how to program the Super NES!
; While all of this this seems extensive now, I hope that in the future we'll all be making original Super FX chip games!
; There's so much creative potential and so much fun to be had!
; --Livvy

;--------training

	messageblue	rob3,<welcome to training!>,other	;72
	messageblue	rob3,<control type a or c are recommended!>,other	;73
	messageblue	rob3,<use l and r to pivot your ship#>,other	;74
	messageblue	rob3,<tap l or r twice to barrel roll!>,other	;75
	messageblue	rob3,<remember to tilt your ship to move faster!>,other	;76
	messageblue	rob3,<barrel rolls are also essential to surviving!>,other	;77
	messageblue	rob3,<use them often!>,other	;78
	messageblue	rob3,<now go on and protect the galaxy!>,other	;79

;--------panther
; NEW
	messagered	panther3,<allow me to introduce myself#>,other	;80
	messagered	panther3,<i am panther! and###>,other	;81
	messagered	panther3,<all who see my rose meet death!>,other	;82
	messagered	panther3,<you'll never get to wolf!>,other	;83   (I think these next two lines (83 & 84) could be taken out.
	messageblue	fox3,<you won't stop me that easily!>,other	;84   "All who see my rose meet death!" is quite the zinger!) --Livvy
	messagered	panther3,<how could this be?!? i-i've been###>,other	;85
; Also, I think Star Panther sounds like a cooler OC name than just Panther.

;--------linktron
; NEW
;5-1
	messageblue	link3,<heaah###!?>,other	;86
	messageblue	link3,<beep boop### hyaaaa!>,other;87
;6-1
	messageblue	link3,<wooow# what are all those heads?>,other	;88
	messageblue	link3,<oh wait, boop# that's me#>,other	;89 ('cause he's a giant head)
;7-1
	messageblue	link3,<beep beep boop#>,other		;90
	messageblue	link3,<yahaha! you found me!>,other	;91
	 messagered	link3,<but none of that matters!>,other	;92
	 messagered	link3,<it's time to bomb some dodongos!>,other	;93
; Leaving messages 92 and 93 here so you know to take them out.
; It might be good to redraw the sprite used here to be a pointy-edged, mechanical Link head instead of, like, his Zelda 3 sprite.
; --Livvy

;NEW
;-------samus
	messageblue	samus3,<greetings, star fox team!>,other	;94
	messageblue	samus3,<you're heading in the right direction#>,other	;95
	messageblue	samus3,<before you go, are you###>,other	;96
	messageblue	samus3,<###in the mood for a challenge?>,other	;97
; Samus fights for peace in the galaxy, so she'd probably be on our side.
; So I thought it'd be cool to change this to a "prove your worth!" kind of situation.
; (If you can't tell I think that messageblue looks the best of all the message colors)
; -- Livvy

;NEW
;-------crimson king
	messageblue	anyone3,<the rusted chains of prison moons###>,other	;98
	messageblue	anyone3,<###are shattered by the sun#>,other	;99
	messageblue	anyone3,<i walk a road, horizons change###>,other	;100
	messageblue	anyone3,<###the tournament's begun#>,other	;101 ; yo kando this last line is currently death text, you'll need to move it
; I like the idea of The Crimson King being a rogue psychological weapon - it kind of looks like The Moment in Doctor Who.
; Except it uses the power of music to bend minds! Maybe Peppy can say "Fox! Plug your ears, quick!"
; This can also be emphasized by fading/switching off the engine noise too.
; I like this too https://genius.com/24734546. Apparently "The Fire Witch" in the song is a weapon or arms dealer? Very cool.
; There shouldn't be any death text, it'd break the mood.
; -- Livvy

;-------craig
	messageblue	craig3,<if master has called me###>,other	;102
	messageblue	craig3,<things must be getting bad!>,other	;103
	messagered	craig3,<come face me! ###craig!>,other	;104
	messagered	craig3,<i###i'm sorry, mar###>,other	;105

;------more rob
	messageblue	rob3,<doing this moves your ship faster!>,other	;106

;------papetoon chatter
	messageblue	fox3,<i barely recognize this place###>,other	;107
	messageblue	fox3,<this is my home? unrecognizable###>,other	;108
	messageblue	fox3,<what happened here? this is awful!>,other	;109

;------papetoon chatter
	messageblue	fox3,<is this### it can't be###>,other	;110
	messageblue	fox3,<why would they do all of this?!>,other	;111
	messageblue	fox3,<someone's gotta pay for all this###>,other	;112

;------------papetoon boss fight
	messagered	toad3,<say, how's the view?>,other	;113
	messageblue	fox3,<what?! who are you?!>,other	;114
	messagered	toad3,<end of the line, fox!>,other	;115
	messageblue	fox3,<wait### is that###>,other	;116
	messagered	toad3,<###hey, how do you steer this thing!?>,other	;117
	messagered	toad3,<noooo!!>,other	;118  ;I'm imagining someone streaming this and doing a funny toad voice :D
; I'm not sure what to do with this lol
; Why does this have to be toad? (jk this is fine)
; I had him say this 'cause he almost hits you and pulls sharply upward shortly afterwards
; --Livvy

;----tarkus stuff
	messageblue	fox3,<everyone! kill your engines, quick!>,other	;119

	messageblue	fox3,<###what happened?>,other	;120
	
	messagered	frog3,<my s-s-ship stopped responding!>,other		;(121)
	messagered	falcon3,<all those meteors were destroyed###>,other		;(122)			part 2
	messagered	rabbit3,<my systems went down momentarily!>,other		;(123)	
	
	messagered	frog3,<we have to be really careful!>,other		;(124)
	messagered	falcon3,<let's take this slow guys###>,other		;(125)			part 2
	messagered	rabbit3,<we should approach with caution, fox#>,other		;(126)	
	
	messageblue	fox3,<follow my lead, team!>,other	;127
	
;----australia

	messageblue	fox3,<this place seems to just repeat###>,other	;128
	messageblue	fox3,<we should reset to get out of here!>,other	;129
	
;---rexius (highly requested!	

	messagered	rex3,<who's making all this noise up here?!>,other	;130
	messagered	rex3,<you're not going any further, punk!>,other	;131
	messageblue	fox3,<stop what you're doing right now!>,other			;132
	messagered	rex3,<i'd like to see you try###>,other		;133
	messagered	rex3,<i'm gonna burn ya up!>,other		;134
	messagered	rex3,<heh, you're not as weak as i thought!>,other		;135
	messagered	rex3,<argh! i'm not done with you yet!>,other	;136
	messagered	rex3,<uarghhh! this is impossible!!>,other	;137

;----training	
	messageblue	rob3,<don't forget to barrel roll!>,other	;138
	messageblue	rob3,<doing this blocks most enemy attacks!>,other	;139
	messageblue	rob3,<banking is important too! hold l or r###>,other	;140
	messageblue	rob3,<to move faster in that direction!>,other	;141

;---hardware detection
	messagered	kando3,<this is bsnes 1#51 based. enjoy!>,other	;142
	messagered	kando3,<you are on mister or analogue pocket! cool!>,other	;143
	messagered	kando3,<this is snes9x based - overclock it!>,other	;144
	messagered	kando3,<wait, this thing runs on zsnes? sorta###>,other	;145
	messagered	kando3,<you are on canoe, nintendo's official emu!>,other	;146
	messagered	kando3,<this is an sd2snes or fxpak! hardware rocks!>,other	;147
	messagered	kando3,<this appears to be bsnes plus# overclock everything!>,other	;148
	messagered	kando3,<mesen - a superb choice#>,other	;149
	messagered	kando3,<ares detected - how accurate!>,other	;150
	messagered	kando3,<actual hardware?! no way!!>,other	;151
	messagered	kando3,<this device is an analogue super nt! cool!>,other	;152
	messagered	kando3,<super fx 3!! rip and tear!!>,other	;153 ; for future use

;----msu-1
	messagered	kando3,<no way! msu-i?! impossible!>,other	;154