	shorta
	longi

	INCPUBLICS	gstrats2.ext


;shiptot equ 584			;model test shapes



shapeslist
.start
	dw	.end-.start
.s1
	dw	a_wing
	dw	paltest1
	dw	paltest2
	dw	texttest1
	dw	falcomod
	dw	slippymod
	dw	foxguy
	dw	hare
	dw	androsshd
	dw	AIR_1
	dw	AMISSILE
	dw	andross
	dw	androsscube
	dw	androsscubee
	dw	arch_0
	dw	ARM
	dw	arwing
	dw	arwing64
	dw	arwingc
	dw	arwingcx
	dw	AUSHOUSE
	dw	barker_l
;	dw	b_wing
	dw	ballz
	dw	BARRIER
	dw	BASE_0
	dw	BASE_0_0
	dw	BASE_0_1
	dw	base_1
	dw	BAZOOKA
	dw	BAZOOKA1
	dw	BAZOOKA2
	dw	bazz_1p
	dw	bazz_1q
	dw	bcruiser_1
	dw	BEEANIM
	dw	big_bird
	dw	big_gate
	dw	BIG_M
	dw	big_meteor
	dw	bigballz
	dw	bigfly
	dw	BIGFROG
	dw	blackro
	dw	BLTUNNELFACE
	dw	blueballz
	dw	BMTUNNELFACE
	dw	bmyship_4
	dw	bmyship_b
	dw	bmyship_l
	dw	bmyship_r
	dw	BOM_WING
	dw	BOSS_0_0
	dw	BOSS_0_0A
	dw	BOSS_0_1
	dw	BOSS_0_2
	dw	BOSS_0_3
	dw	BOSS_1_0
	dw	BOSS_1_1
	dw	BOSS_1_2
	dw	BOSS_2_0
	dw	BOSS_2_1
	dw	BOSS_2_2
	dw	BOSS_2_3
	dw	BOSS_2_4
	dw	BOSS_2_5
	dw	BOSS_2_6
	dw	BOSS_7_0
	dw	BOSS_7_1
	dw	BOSS_7_1O
	dw	BOSS_7_2
	dw	BOSS_7_3
	dw	BOSS_7_4
	dw	BOSS_8_0
	dw	BOSS_8_1
	dw	BOSS_8_1C
	dw	BOSS_8_4
	dw	BOSS_8_5
	dw	BOSS_9_0
	dw	boss_9_5
	dw	BOSS_A_1
	dw	BOSS_A_2
	dw	BOSS_A_3
	dw	BOSS_A_4
	dw	BOSS_A_5
	dw	BOSS_A_6
	dw	BOSS_B_0
	dw	BOSS_B_1
	dw	BOSS_B_6
	dw	BOSS_B_7
	dw	BOSS_B_H
	dw	BOSS_B_L
	dw	BOSS_B_R
	dw	BOSS_D_0
	dw	BOSS_D_1
	dw	BOSS_D_2
	dw	BOSS_D_4
	dw	BOSS_D_5
	dw	BOSS_D_6
	dw	BOSS_D_7
	dw	BOSS_D_8
	dw	BOSS_D_9
	dw	BOSS_D_A
	dw	BOSS_E_0
	dw	BOSS_E_1
	dw	BOSS_E_1A
	dw	BOSS_E_3
	dw	BOSS_E_4
	dw	BOSS_F_0
	dw	BOSS_F_1
	dw	BOSS_F_2
	dw	BOSS_F_3
	dw	BOSS_F_4
	dw	BOSS_F_5
	dw	BOSS_F_6
	dw	BOSS_F_7
	dw	BOSS_F_8
	dw	BOSS_F_8A
	dw	BOSS_F_9
	dw	BOSS_F_9A
	dw	BOSS_F_B
	dw	BOSS_G_0
	dw	boss_g_s
	dw	boss_h_0
	dw	boss_h_1
	dw	boss_h_1a
	dw	boss_h_2
	dw	boss_h_3
	dw	bou_0
	dw	bou_1
	dw	bou_1b
	dw	bowser
	dw	bowsermad
	dw	boxxie
	dw	brokenbu
	dw	bship_0_1
;	dw	BSHIPEXITFACE
	dw	BU_0
	dw	BU_1
	dw	BU_2
	dw	BU_3
	dw	BU_4
	dw	BU_5
	dw	BU_6
	dw	BU_7
	dw	BULGE
	dw	bullfrog
	dw	BWARKER_3
	dw	c_miss
	dw	c_robo
	dw	c_wing
	dw	CAMELEON
	dw	car_0
	dw	car_10
	dw	CARRIER
	dw	catpaw
	dw	cfighter
	dw	clisla_L
	dw	clisla_m
	dw	clisla_S
	dw	clrunner
	dw	cobramk3
	dw	COCKPIT
	dw	COLONY_0
	dw	COLONY_1
	dw	COLONY_2
	dw	COLONY3L
	dw	COLONY3R
	dw	CORE_1_0
	dw	CORE_1_1
	dw	CORNCRUISELASER
	dw	corncruiser
	dw	cornfriend
	dw	crab
	dw	cricket
	dw	D_ASHI_L
	dw	D_ASHI_R
	dw	D_BODY_0
	dw	D_HEAD_0
	dw	d_pilar
	dw	deboss_0
	dw	deboss_2
	dw	delta
	dw	DFX
	dw	DJPA
	dw	DODORA_0
	dw	DODORA_1
	dw	DODORA_2
	dw	DODORA_3
	dw	DODORA_L
	dw	DODORA_R
	dw	DOOR_1
	dw	DRAGON_HEAD
	dw	DRAIL_0
	dw	DRAIL_4
	dw	drone5
	dw	drwing
	dw	EISEI_0
	dw	ELASER2
	dw	ELASER2A
	dw	elaserfire
	dw	enemy_o_1
	dw	enemy5v
	dw	escapee
	dw	EXIT_0
	dw	EXIT_1
	dw	EXIT_2
	dw	EXITFACE
	dw	EXITLIGHT
	dw	EXPL_4
	dw	EXPL_6
	dw	EXPL_8
	dw	EXPLOSION
	dw	EXPLOSION2
	dw	EXPLOSION3
	dw	EXPLOSION4
	dw	explosion5
	dw	F_DRA_1
	dw	F_DRAGON
	dw	F_FISH
	dw	face_0
	dw	face_0_1
	dw	face_1
	dw	face_b
	dw	face_box
	dw	falco1
	dw	falco2
	dw	FCTA
	dw	fireballz
	dw	FIREBREATH
	dw	fireface_B
	dw	fireface1_B
	dw	flingboss
	dw	flower
	dw	flower_1
	dw	flower_2
	dw	flyingbug
	dw	font_d
	dw	font_d2
	dw	font_e
	dw	font_e2
	dw	font_e3
	dw	font_h
	dw	font_h2
	dw	font_n
	dw	font_n2
	dw	font_t
	dw	font_t2
	dw	friendship_4
	dw	g_mount
	dw	gamesh
	dw	GATE_0
	dw	GATE_1
	dw	gate_2
	dw	grabber
	dw	GRO_5
	dw	grtfox
	dw	guard_0
	dw	half_d
	dw	hand_l
	dw	hand_r
	dw	HAPPYFACESHIP
	dw	HELI
	dw	helpball
	dw	HILLHOIST
	dw	HOU_3
	dw	HOU_4
	dw	HOU_5
	dw	HOU_L
	dw	HOU_R
	dw	HOUDAI_0
	dw	HOUDAI_1
	dw	hoverboss
	dw	HUMANA
	dw	HYPER
	dw	HYPER2
	dw	HYPER3
	dw	HYPER4
	dw	icarus
	dw	ika
	dw	imyship_4
	dw	IRIS
	dw	iris_1
	dw	ITEM_0
	dw	ITEM_4
	dw	ITEM_5
	dw	ITEM_6
	dw	ITEM_7
	dw	k_base_0
	dw	k_base_2
	dw	k_door
	dw	KAMI_S
	dw	KAMIKAZE
	dw	kandologocube
	dw	KANGA
	dw	KELLOGS
	dw	KICHI_0
	dw	KICHI_1
	dw	KICHI_2
	dw	KICHI_3
	dw	laserline
	dw	last_b_0
	dw	last_b_3
	dw	LBLACKFACE
	dw	leaf
	dw	LENG_0
	dw	LINE
	dw	LINE_2
	dw	LINE2
	dw	LINE3
	dw	LINKHEAD
	dw	LMARK
	dw	LMISSILE
	dw	lock_man
	dw	LOG
	dw	long_bridge
	dw	LONGFACE
	dw	LUIGIH
	dw	LWIREEXIT
	dw	M_TANK
	dw	MACCAS
	dw	MAGPIE
	dw	mantis
	dw	MARIOH
	dw	MBLACKFACE
	dw	meteo_0
	dw	MEXITFACE
	dw	MINE_0
	dw	MINE_0_S
	dw	mine_2
	dw	minispider
	dw	MISS_1_1
	dw	MISS_1_2
	dw	MISSILE
	dw	MMARK
	dw	MONIKRUISER
	dw	morw
	dw	MWIREEXIT
	dw	MY_B_W
	dw	my_bird
	dw	MY_DEMO
	dw	my_demoS
	dw	MY_L_W
	dw	MY_R_W
	dw	MY_UP
	dw	mybase_0
	dw	MYBASE_1
	dw	MYSHIP_4
	dw	MYSHIP_B
	dw	MYSHIP_L
	dw	MYSHIP_R
	dw	myship2
	dw	myzoom_4
	dw	myzoom_b
	dw	myzoom_l
	dw	myzoom_r
	dw	n64con
	dw	NECK
	dw	ninja_0
	dw	ninja_1
	dw	ninja_2
	dw	ninja_enemy
	dw	old_type2
	dw	op_0
	dw	op_1
	dw	op_2
	dw	op_2new
	dw	oversh
	dw	palmtree
	dw	paper_1
	dw	paper_3
	dw	PARA_0
	dw	PARA_1
	dw	peppy1
	dw	peppy2
	dw	PETECUBE
	dw	PEXPLOD
	dw	PHAZER
	dw	PIERROT
	dw	pilar3
	dw	PILLAR2
	dw	PILLAR3
	dw	pillar3_ns
	dw	pilon
	dw	pinetree
	dw	pipe_0
	dw	pipe_1
	dw	pipe_2
	dw	pipe_3
	dw	pipe_4
	dw	pipe_5
	dw	pipe_6
	dw	pipe_8
	dw	pipe_8_0
	dw	pipe_9
	dw	pipe_9_0
	dw	PLANE1
	dw	playertwo1
	dw	POINTYANIM
	dw	pole_0
	dw	quadcrab
	dw	quadwing
	dw	R_BU_0
	dw	R_BU_1
	dw	R_BU_2
	dw	R_BU_3
	dw	R_BU_4
	dw	R_BU_5
	dw	R_BU_6
	dw	R_BU_7
	dw	R_BUT_2
	dw	R_HOU_0
	dw	RADER_0
	dw	RADER_1
	dw	rail_4
	dw	ray_0
	dw	ray_1
	dw	ray_blue
	dw	ray_bred
	dw	rex_b
	dw	rex_b2
	dw	rex_b3
	dw	rex_f_l
	dw	rex_f_l2
	dw	rex_f_l3
	dw	rex_f_r
	dw	rex_f_r2
	dw	rex_f_r3
	dw	RIPAIR_W
	dw	RO_0
	dw	RO_1
	dw	RO_2
	dw	RO_3
	dw	RO_4
	dw	RO_5
	dw	RO_6
	dw	robosf2
	dw	robot_0
	dw	ROUND_0
	dw	round0p
	dw	rpillar3
	dw	ryousan
	dw	S_0
	dw	S_1
	dw	S_DOOR_1
	dw	S_DOOR_2
	dw	s_fish
	dw	S_HOU_0
	dw	S_TANK_0
	dw	SAUSHAD
	dw	scarrier01
	dw	SCHOOLZONE
	dw	SCORPION
	dw	SEA_0
	dw	SEA_0_0
	dw	SEA_0_1
	dw	SF2BLIMP
	dw	sf2missile
	dw	sface_b
	dw	sface2_b
	dw	SGALPHA
	dw	SHARK
	dw	SHARK1
	dw	shelpball
	dw	shieldr
	dw	SHIP_0_C
	dw	SHIP_1
	dw	SHIP_1_S
	dw	SHIP_3
	dw	SHIP_3_S
	dw	SHIP_4
	dw	SHIP_5
	dw	SHIP_5M
	dw	ship_5s
	dw	SHIP_S_0
	dw	SHIP_S_1
	dw	SHIP3EXITFACE
	dw	SHIPS
	dw	SHRAP1
	dw	SHYPER
	dw	SJPA
	dw	skyb
	dw	skyclaw
	dw	slippy1
	dw	slippy2
	dw	slot_0
	dw	slot_1
	dw	slot_2
	dw	slot_3
	dw	slot_4
	dw	SMALL_M
	dw	smallballz
	dw	SMARK
	dw	snake_0
	dw	snake_1
	dw	snake_2
	dw	snake_3
	dw	snake_4
	dw	spacepilon
	dw	spaceplane
	dw	SPARKLAS
	dw	SPEXPLOD
	dw	SSHIP_0_C
	dw	stalk
	dw	stalk_1
	dw	SXPSOLIDSPACEBAR
	dw	SXPWIRESPACEBAR
	dw	SXSOLIDSPACEBAR
	dw	SXWIRESPACEBAR
	dw	SYSOLIDSPACEBAR
	dw	SYWIRESPACEBAR
	dw	SZSOLIDSPACEBAR
	dw	SZWIRESPACEBAR
	dw	t_ex_1
	dw	t_ex_2
	dw	tadcol
	dw	tadpole
	dw	TAIGUN
	dw	TANK_1
	dw	TANK_2
	dw	TEKIKAN
	dw	TOTEM_2
	dw	tow_0
	dw	tow_1
	dw	TOWER_2
	dw	tower_2a
	dw	trainingring
	dw	tree
	dw	TRUCK
	dw	TUNNEL_0
	dw	ULURU
	dw	UP1_MAN
	dw	UPER_M
	dw	viper01
;	dw	vixiv
	dw	W_L
	dw	walk_4_0
	dw	walk_4_l
	dw	walk_4_r
	dw	WALKER_0
	dw	WALKER_2
	dw	WALKER_L
	dw	WALKER_R
	dw	WALL_0
	dw	WALL_2
	dw	WALL_4
	dw	WALL_5
	dw	WALL_L
	dw	WALL_R
	dw	WALL1
	dw	WARKER_3
	dw	WARP
	dw	WARP_1
	dw	WARP_2
	dw	WARP_3
	dw	whale
	dw	whale1
	dw	WINDMILLAUS
	dw	Winnebago
	dw	WIRE_MAN
	dw	wired
	dw	WIREPLAYERTWO
	dw	wolf
	dw	wolf_1
	dw	wolfen
	dw	wolfen64
	dw	XPSOLIDSPACEBAR
	dw	XPSOLIDSPACEBARROTY
	dw	XPWIRESPACEBAR
	dw	XPWIRESPACEBARROTY
	dw	XSOLIDSPACEBAR
	dw	XWIRESPACEBAR
	dw	xzship
	dw	yellowbird
	dw	yfighter
	dw	yoshianm
	dw	yoshiblack
	dw	yoshiblue
	dw	yoshired
	dw	YSOLIDSPACEBAR
	dw	YWIRESPACEBAR
	dw	zaco_0
	dw	zaco_1
	dw	ZACO_4
	dw	ZACO_4p
	dw	ZACO_5
	dw	ZACO_6
	dw	ZACO_7
	dw	ZACO_7p
	dw	ZACO_8
	dw	ZACO_8p
	dw	ZACO_9
	dw	zaco_a
	dw	zaco_b
	dw	ZSOLIDSPACEBAR
	dw	ZWIRESPACEBAR
	dw	nullshape
.s2
	dw	.end-.start
.end
	dw	0

shiptot equ (.s2-.s1)/2		;model test shapes

	
	structure	shapeslist
	struct		shape_size,1
	struct		shape_text,0

;-----------------TARGET LIST-------------------------------
targetlist
	dw	target_1
	dw	target_1blue
	dw	target_1green
	dw	target_1red
	dw	target_1yellow
	dw	target_1white
	dw	0
	
	
xhairlist
.s1
	dw	xhaircube2
	dw	xhaircube3
	dw	xhaircube4
	dw	xhaircube5
	dw	xhaircube6
	dw	xhaircube7
	dw	xhaircube8
	dw	xhaircube9
;	dw	xhaircube10
;	dw	xhaircube11
;	dw	xhaircube12
;	dw	xhaircube13
;	dw	xhaircube14
;	dw	xhaircube15
;	dw	xhaircube16
;	dw	xhaircube17
	dw	gxhaircube1
	dw	gxhaircube2
	dw	gxhaircube3
	dw	gxhaircube4
	dw	bxhaircube1
	dw	bxhaircube3
	dw	bxhaircube4
	dw	yxhaircube1
	dw	yxhaircube2
	dw	yxhaircube3
	dw	yxhaircube4
	dw	rxhaircube1
	dw	rxhaircube2
.s2
	dw	nullshape
	dw	0
xhairtot	equ	(.s2-.s1)/2

xhairreallist
.s1
	dw	xhair2
	dw	xhair3
	dw	xhair4
	dw	xhair5
	dw	xhair6
	dw	xhair7
	dw	xhair8
	dw	xhair9
;	dw	xhair10
;	dw	xhair11
;	dw	xhair12
;	dw	xhair13
;	dw	xhair14
;	dw	xhair15
;	dw	xhair16
;	dw	xhair17
	dw	gxhair1
	dw	gxhair2
	dw	gxhair3
	dw	gxhair4
	dw	bxhair1
	dw	bxhair3
	dw	bxhair4
	dw	yxhair1
	dw	yxhair2
	dw	yxhair3
	dw	yxhair4
	dw	rxhair1
	dw	rxhair2
.s2
	dw	nullshape
	dw	0
xhairrealtot	equ	(.s2-.s1)/2






;-----------------SHIP LIST-------------------------------

shiplistshape
.s
	dw	myship_4					;0
	dw	wired						;1
	dw	nullshape
	dw	my_up
	dw	nullshape					
	dw	Bmyship_4					;5
	dw	myzoom_4
	dw	xzship
	dw	skyb
	dw	bullfrog					
	dw	morw						;10
	dw	delta
	dw	catpaw
	dw	skyclaw
	dw	cfighter					
	dw	arwingcx					;15
	dw	clrunner
	dw	arwingc
	dw	tadcol
	dw	grtfox						
	dw	wolfen						;20
	dw	blackro
	dw	wolfen64
	dw	arwing64
	dw	plane1						
	dw	my_demoS					;25
	dw	old_type2
	dw	ryousan
	dw	a_wing
	dw	b_wing						
	dw	c_wing						;30
	dw	c_robo
.dfx
	dw	dfx
	dw	fcta
	dw	sjpa						
.djpa
	dw	djpa						;35
.cobra
	dw	cobramk3
	dw	wiredsp
	dw	bmyship_4
	dw	myship2
	dw	wolf						;40
	dw	wolf_1
	dw	sf2missile
	dw	drwingp
	dw	yellowbirdp
	dw	smallballzp					;45
	dw	guard_0p
	dw	EISEI_0p
	dw	TAIGUNp
	dw	tekikanp
	dw	ninja_enemyp				;50
	dw	petecube
	dw	androsscubee
	dw	ray_bluep
	dw	ray_bredp					;54
	dw	ray_0p
	dw	wire_manp
.cockpit
	dw	cockpit2
	dw	f_fishp				
	dw	tadpolep					;59
	dw	whale1
	dw	my_birdp
	dw	shark1
	dw	zaco_1p				
	dw	zaco_5p						;64
	dw	zaco_6p
	dw	zaco_8pl
	dw	zaco_ap
	dw	zaco_bp				
	dw	helip						;69
	dw	ikap
	dw	f_dragonp
	dw	air_1p
	dw	car_10p				
	dw	phazer						;74
	dw	boss_d_ap					;75
	dw	icarus						;76
	dw	slippy1						;77
	dw	falco1						;78
	dw	peppy1						;79
	dw	yfighter					;80
	dw	sgalpha						;81
	dw	quadwing					;82
	dw	monikruiser					;83
	dw	nullshape					;84 ; should always be at the end, add new shapes before this one
.e
;----end of selectable list
	dw	myship_r			;unselectable
	dw	myship_l			;unselectable
	dw	myship_b			;unselectable
	
;add ships to the above list, set the total number below here and in title.asm

shipcount equ ((.e-.s)/2)-1		;selectable ship shapes last number (nullshape)

dfxspot equ ((.dfx-.s)/2)		;stratmac

djpaspot equ ((.djpa-.s)/2)		;stratmac

cobraspot equ ((.cobra-.s)/2)	;stratmac

cockpitspot equ ((.cockpit-.s)/2)	;stratmac

	strats_start





;*****************************************************************************

float256_srou_l
	jsr			flout_srou
	s_set_var2vartab	B,B,W,tpx,x1,sintab,-1
	s_set_var2vartab	B,B,W,tpy,x2,sintab,-1
	jmp			float_cont

float128_srou_l
	jsr			flout_srou
	s_set_var2vartab	B,B,W,tpx,x1,sintab,-2
	s_set_var2vartab	B,B,W,tpy,x2,sintab,-2
	jmp			float_cont

float64_srou_l
	jsr			flout_srou
	s_set_var2vartab	B,B,W,tpx,x1,sintab,-3
	s_set_var2vartab	B,B,W,tpy,x2,sintab,-3
	jmp			float_cont

float32_srou_l
	jsr			flout_srou
	s_set_var2vartab	B,B,W,tpx,x1,sintab,-4
	s_set_var2vartab	B,B,W,tpy,x2,sintab,-4


float_cont
	s_add_alvar		W,x,al_worldx,tpx
	s_add_alvar		W,x,al_worldy,tpy
	s_rtl
flout_srou
	lda			floatvar1
	stx			x1
	clc
	adc			x1
	sta			x1

	lda			floatvar2
	stx			x2
	clc
	adc			x2
	sta			x2

	rts

selectnextship_l
	jsr	selectnextship
	rtl
	
selectnextship
	php								;Push processor Status (?)			;---;			|
	phb								;Push data bank register (?)		;---;			|
	a8i16							;8 bit accumulator, 16 bit index	;---;			|
																		;---;
	lda	#$7e						;Load $7E bank						;---;	
	plb								;Pull data bank register			;---;

	lda	curr_ship
	jsl			select_nextship_l
	plp
	rts

selectprevship_l
	jsr	selectprevship
	rtl

selectprevship
	php								;Push processor Status (?)			;---;			|
	phb								;Push data bank register (?)		;---;			|
	a8i16							;8 bit accumulator, 16 bit index	;---;			|
																		;---;
	lda	#$7e						;Load $7E bank						;---;	
	plb								;Pull data bank register			;---;
	lda	curr_ship

	jsl			select_prevship_l
	plp
	rts

nextweapon_l
	jsr	nextweapon
	rtl
	
nextweapon
	lda	weaponnumberpone
	cmp	#29
	beq	.goto98
	cmp	#99
	lbeq	.weapreset
	inc	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc6
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc6
	;s_copy_var2alvar	W,x,al_shipnum,shiptemp
	lda	weaponnumberpone
	cmp	#17
	lbeq	.resetweaptable


	lda	weapnextptr
	sta	weapptr
	jmp	.noch
.goto98
	lda	#98
	sta	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc99
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc99
	;s_copy_var2alvar	W,x,al_shipnum,shiptemp
	lda	weaponnumberpone
	cmp	#17
	lbeq	.resetweaptable

	lda	weapnextptr
	sta	weapptr
	bra	.noch
.weapreset
	lda	#0
	sta	weaponnumberpone
	stz	weapptr
	stz	weapnextptr
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc9
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc9
	;s_copy_var2alvar	W,x,al_shipnum,shiptemp
	lda	weaponnumberpone
	cmp	#17
	beq	.resetweaptable
	lda	weapnextptr
	sta	weapptr
	bra	.noch
.resetweaptable
	stz	weapptr
	stz	weapnextptr
.noch
	rts

prevweapon_l
	jsr	prevweapon
	rtl
	
prevweapon
	lda	weaponnumberpone
	cmp	#0
	lbeq	.weaprestart
	cmp	#17
	beq	.bridgetables
	cmp	#98
	lbeq	.from98
	dec	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc8
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc8
	lda	weaponnumberpone
	cmp	#17
	bpl	.looper1secondtable
	lda	weapptr
	tax
	dex
.looper1
	dex
	lda.l	weaponslist,x
	lbeq	.doneloop1
	cmp	#1

	beq	.doneloop1
	bra	.looper1
.looper1secondtable
	lda	weapptr
	tax
	dex
.looper12
	dex
	lda.l	weaponslist2,x
	lbeq	.doneloop1
	cmp	#1

	beq	.doneloop1
	bra	.looper12

	
.doneloop1

	dex
	txa
	sta	weapptr
	
	jmp	.nochh
;-------	
.bridgetables
	dec	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc8t
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc8t
	lda	#194
	sta	weapptr
	jmp	.nochh
;------------
.from98
	lda	#29
	sta	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc999
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc999
	lda	weaponnumberpone
	cmp	#17
	bpl	.looper2secondtable
	lda	weapptr
	tax
	dex
.looper2
	dex
	lda.l	weaponslist,x
	beq	.doneloop2
	cmp	#1
	beq	.doneloop2
	bra	.looper2
.looper2secondtable	
	lda	weapptr
	tax
	dex
.looper22
	dex
	lda.l	weaponslist2,x
	beq	.doneloop2
	cmp	#1
	beq	.doneloop2
	bra	.looper22
	
.doneloop2

	dex
	txa
	sta	weapptr



	bra	.nochh
.weaprestart
	lda	#99
	sta	weaponnumberpone
	s_copy_var2alvar	W,x,al_weaponnum,weaponnumberpone
	s_copy_var2var		B,shiptemp,curr_ship
	lda	shiptemp
	cmp	#0
	beq	.calc7
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
	dec	shiptemp
.calc7
	lda	#187			;pointer for weapon 99 text start position
	sta	weapptr



	bra	.nochh
.nochh
	rts


assault1_Istrat			;Peppy
	s_start_strat
	s_set_alptrs	x,assault1_strat,hitflash_Istrat,0
	s_set_aldata	x,#100,#friendAP
	s_set_colltype	x,friend
	s_setnoremove_behind	x
	s_set_alsflag	x,shadow
	s_set_alsflag		x,playerobj
	s_end_strat
assault1_strat
	s_start_strat
	s_set_alvar			B,x,al_openal,#0

	s_gen_3dvecs		x,al_roty,al_rotx,al_speed
	s_add_vecs2pos		x
	s_jmp_higher		x,#-30,.ok
	s_set_alvar		W,x,al_worldy,#-30
.ok

	lda	twoplayer
	cmp	#0
	lbeq	nomorep2
	s_set_objtobeplayer	y
	s_copy_alvar2alvar	B,x,al_speed,y,al_speed
	a16
	lda.w		al_worldx,y
	clc
	adc	#80
	sta	playeronex
	lda.w		al_worldy,y
	sta	playeroney
	a8
;	s_copy_vecs		x,y 

	s_copy_alvar2alvar.w	W,x,al_worldz,y,al_worldz
	s_add_alvar		W,x,al_worldz,#190

	s_jmp_alvarZERO		W,x,al_sword1,.dofind
	s_set_objtobealvar	y,x,al_sword1
	s_jmp_Zdistless		x,y,#400,.dofind2
;	s_jmp_alvarNOTZERO.w	B,y,al_HP,.skipfind
.dofind2	LOCAL
	s_set_alvar		W,x,al_sword1,#0

.dofind	s_set_find		0
.find	
	s_find_radiusobj	y,x,#0,#0,#2000,.nofind
	s_jmp_alvarEQ.w		B,y,al_openal,#2,.find
	s_jmp_alvarEQ.w		B,y,al_openal,#3,.find
;	s_jmp_alsflag		y,lockon,.find
;	s_jmpNOT_colltype	y,Zenemy,.find
	s_jmp_colltype	y,friend,.find
	s_jmp_colltype	y,laser,.find
	s_jmp_alsflag		y,nohitaffect,.find
	s_jmp_alsflag		y,colldisable,.find
;	s_jmp_alvarEQ.w		B,y,al_hp,#hardHP,.find
	s_cmp_alvar			W,y,al_stratptr,0
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#arm
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#boss_2_5
	lbeq					.find

	a16
	lda.w			al_worldx,y
	sec
	sbc			playeronex
	bpl			.nneg
	nega
.nneg
	sta			tpa
	
	lda.w			al_worldz,y
	sec
	sbc			player_posz
	lbmi			.find	

	cmp			tpa
	a8
	lbmi			.find	

	s_set_alvartobeobj	x,al_sword1,y
	s_set_alsflag		y,lockon
	lda	#1
	sta	testforassault

.skipfind
	s_jmp_notdelay		2,.found
	s_weapon_pos		#0,#0,#80
	s_weapon_rot		#0,#0
	phy
	s_fire_weapon		x,ELASER
	ply
;	inc	teamshots
;	lda	teamshots
;	cmp	#60
;	lbpl	.end
	s_brl			.found
.nofind
	inc	testforassault
	lda			testforassault
	cmp	#1
	beq	.1
	bra	.7
.1
	s_jmp			assault2_strat.dofind2
.7		;exit
	s_jmp			assaultall_strat.dofind2
	s_achase_alvar		B,x,al_roty,#0,5
	s_achase_alvar		B,x,al_rotx,#0,5

	s_achase_alvar		W,x,al_worldx,playeronex,5
	s_achase_alvar		W,x,al_worldy,playeroney,5


	s_brl			.cont

.found
;	s_set_alsflag		y,hitflash
	s_obj2obj_3dangle	x,y,al_roty,al_rotx,5

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarless		W,x,al_worldy,maxpmoveY,.nfpbottom	;
	s_set_alvar		W,x,al_worldy,maxpmoveY					;

	s_test_var		B,pmovelimitAND,#pml_Bbottom			;
	s_bne			.nfpbottom								;
	s_or_var		B,arrows,#sprar_down					;
	s_sub_alvar		W,x,al_worldy,#5
	bra	.top
.nfpbottom													;limit up and down movement
													;
;	s_jmp_alvarlessEQ		W,x,al_worldy,maxpmoveY-10,.change
;	bra	.top
;.change
;	s_achase_alvar		B,x,al_rotx,#0,1															;
	
.top
	s_jmp_alvarmore		W,x,al_worldy,minpmoveY,.nfptop		;
	s_set_alvar		W,x,al_worldy,minpmoveY					;
	s_or_var		B,arrows,#sprar_up						;
;	s_add_alvar		W,x,al_worldy,#5
.nfptop														;

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarmore	W,x,al_worldX,minpmoveX,.nminX
	s_set_alvar	W,x,al_worldX,minpmoveX
	s_or_var		B,arrows,#sprar_left
	s_add_alvar		W,x,al_worldx,#5
.nminX
	s_jmp_alvarless	W,x,al_worldX,maxpmoveX,.nmaxX
	s_set_alvar	W,x,al_worldX,maxpmoveX						;limit left/right movement
	s_or_var		B,arrows,#sprar_right
	s_sub_alvar		W,x,al_worldx,#5
.nmaxX
;-----------------------------------------------------------------------------------
.cont

	LDA	AL_ROTY,X
	ASL	A
	ASL	A
	STA	AL_ROTZ,X
	
	s_end_strat

.end

;	stz	teamshots
	stz	teamon
	s_remove_offscn	x

	s_set_path		x,flyawayplease
	
.endrem	
	s_set_strat		x,0
	s_end_strat
;---------------------------------------------------------------------	

assault2_Istrat			;Falco
	s_start_strat
	s_set_alptrs	x,assault2_strat,hitflash_Istrat,0
	s_set_aldata	x,#100,#friendAP
	s_set_colltype	x,friend
	s_setnoremove_behind	x
	s_set_alsflag	x,shadow
	s_set_alsflag		x,playerobj
	s_end_strat
assault2_strat
	s_start_strat

	lda	#4
	sta	testforassault
	s_gen_3dvecs		x,al_roty,al_rotx,al_speed
	s_add_vecs2pos		x
	s_jmp_higher		x,#-30,.ok
	s_set_alvar		W,x,al_worldy,#-30
.ok

	lda	twoplayer
	cmp	#0
	lbeq	nomorep2
	s_set_objtobeplayer	y
	s_copy_alvar2alvar	B,x,al_speed,y,al_speed
	a16
	lda.w		al_worldx,y
	sec
	sbc	#120
	sta	playeronex
	lda.w		al_worldy,y
	sta	playeroney
	a8
;	s_copy_vecs		x,y 

	s_copy_alvar2alvar.w	W,x,al_worldz,y,al_worldz
	s_add_alvar		W,x,al_worldz,#250

	s_jmp_alvarZERO		W,x,al_sword1,.dofind
	s_set_objtobealvar	y,x,al_sword1
	s_jmp_Zdistless		x,y,#400,.dofind2
;	s_jmp_alvarNOTZERO.w	B,y,al_HP,.skipfind
.dofind2	LOCAL
	s_set_alvar		W,x,al_sword1,#0

.dofind	s_set_find		0
.find	
	s_find_radiusobj	y,x,#0,#0,#2000,.nofind
	
;	s_jmp_alsflag		y,lockon,.find
;	s_jmpNOT_colltype	y,Zenemy,.find
	s_jmp_alvarEQ.w		B,y,al_openal,#1,.find
	s_jmp_alvarEQ.w		B,y,al_openal,#3,.find
	s_jmp_colltype	y,friend,.find
	s_jmp_colltype	y,laser,.find
	s_jmp_alsflag		y,nohitaffect,.find
	s_jmp_alsflag		y,colldisable,.find
;	s_jmp_alvarEQ.w		B,y,al_hp,#hardHP,.find
	s_cmp_alvar			W,y,al_stratptr,0
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#arm
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#boss_2_5
	lbeq					.find

	a16
	lda.w			al_worldx,y
	sec
	sbc			playeronex
	bpl			.nneg
	nega
.nneg
	sta			tpa
	
	lda.w			al_worldz,y
	sec
	sbc			player_posz
	lbmi			.find	

	cmp			tpa
	a8
	lbmi			.find	

	s_set_alvartobeobj	x,al_sword1,y
	s_set_alsflag		y,lockon
	s_set_alvar			B,y,al_openal,#2

.skipfind
	s_jmp_notdelay		2,.found
	s_weapon_pos		#0,#0,#80
	s_weapon_rot		#0,#0
	phy
	s_fire_weapon		x,ELASER
	ply
;	inc	teamshots
;	lda	teamshots
;	cmp	#60
;	lbpl	.end
	s_brl			.found
.nofind
	inc	testforassault
	lda	testforassault
	cmp	#5
	beq	.2
	bra	.11
.2
	s_jmp			assault3_strat.dofind2

.11	;exit
	s_jmp			assaultall_strat.dofind2	
	s_achase_alvar		B,x,al_roty,#0,5
	s_achase_alvar		B,x,al_rotx,#0,5

	s_achase_alvar		W,x,al_worldx,playeronex,5
	s_achase_alvar		W,x,al_worldy,playeroney,5


	s_brl			.cont

.found
;	s_set_alsflag		y,hitflash
	s_obj2obj_3dangle	x,y,al_roty,al_rotx,4

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarless		W,x,al_worldy,maxpmoveY,.nfpbottom	;
	s_set_alvar		W,x,al_worldy,maxpmoveY					;

	s_test_var		B,pmovelimitAND,#pml_Bbottom			;
	s_bne			.nfpbottom								;
	s_or_var		B,arrows,#sprar_down					;
	s_sub_alvar		W,x,al_worldy,#5
	bra	.top
.nfpbottom													;limit up and down movement
													;
;	s_jmp_alvarlessEQ		W,x,al_worldy,maxpmoveY-10,.change
;	bra	.top
;.change
;	s_achase_alvar		B,x,al_rotx,#0,1															;
	
.top
	s_jmp_alvarmore		W,x,al_worldy,minpmoveY,.nfptop		;
	s_set_alvar		W,x,al_worldy,minpmoveY					;
	s_or_var		B,arrows,#sprar_up						;
;	s_add_alvar		W,x,al_worldy,#5
.nfptop														;

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarmore	W,x,al_worldX,minpmoveX,.nminX
	s_set_alvar	W,x,al_worldX,minpmoveX
	s_or_var		B,arrows,#sprar_left
	s_add_alvar		W,x,al_worldx,#5
.nminX
	s_jmp_alvarless	W,x,al_worldX,maxpmoveX,.nmaxX
	s_set_alvar	W,x,al_worldX,maxpmoveX						;limit left/right movement
	s_or_var		B,arrows,#sprar_right
	s_sub_alvar		W,x,al_worldx,#5
.nmaxX
;-----------------------------------------------------------------------------------
.cont

	LDA	AL_ROTY,X
	ASL	A
	ASL	A
	STA	AL_ROTZ,X
	
	s_end_strat

.end

;	stz	teamshots
	stz	teamon
	s_remove_offscn	x

	s_set_path		x,flyawayplease
	
.endrem	
	s_set_strat		x,0
	s_end_strat





assault3_Istrat			;Slippy
	s_start_strat
	s_set_alptrs	x,assault3_strat,hitflash_Istrat,0
	s_set_aldata	x,#100,#friendAP
	s_set_colltype	x,friend
	s_setnoremove_behind	x
	s_set_alsflag	x,shadow
	s_set_alsflag		x,playerobj
	s_end_strat
assault3_strat
	s_start_strat
	lda	#8
	sta	testforassault

	s_gen_3dvecs		x,al_roty,al_rotx,al_speed
	s_add_vecs2pos		x
	s_jmp_higher		x,#-30,.ok
	s_set_alvar		W,x,al_worldy,#-30
.ok

	lda	twoplayer
	cmp	#0
	lbeq	nomorep2
	s_set_objtobeplayer	y
	s_copy_alvar2alvar	B,x,al_speed,y,al_speed
	a16
	lda.w		al_worldx,y
	sta	playeronex
	lda.w		al_worldy,y
	sec
	sbc	#100
	sta	playeroney
	a8
;	s_copy_vecs		x,y 

	s_copy_alvar2alvar.w	W,x,al_worldz,y,al_worldz
	s_add_alvar		W,x,al_worldz,#140

	s_jmp_alvarZERO		W,x,al_sword1,.dofind
	s_set_objtobealvar	y,x,al_sword1
	s_jmp_Zdistless		x,y,#400,.dofind2
;	s_jmp_alvarNOTZERO.w	B,y,al_HP,.skipfind
.dofind2	LOCAL
	s_set_alvar		W,x,al_sword1,#0

.dofind	s_set_find		0
.find	
	s_find_radiusobj	y,x,#0,#0,#2000,.nofind
	s_jmp_alvarEQ.w		B,y,al_openal,#1,.find
	s_jmp_alvarEQ.w		B,y,al_openal,#2,.find	
;	s_jmp_alsflag		y,lockon,.find
;	s_jmpNOT_colltype	y,Zenemy,.find

	s_jmp_colltype	y,friend,.find
	s_jmp_colltype	y,laser,.find
	s_jmp_alsflag		y,nohitaffect,.find
	s_jmp_alsflag		y,colldisable,.find
;	s_jmp_alvarEQ.w		B,y,al_hp,#hardHP,.find
	s_cmp_alvar			W,y,al_stratptr,0
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#arm
	lbeq					.find
	s_cmp_alvar			W,y,al_shape,#boss_2_5
	lbeq					.find

	a16
	lda.w			al_worldx,y
	sec
	sbc			playeronex
	bpl			.nneg
	nega
.nneg
	sta			tpa
	
	lda.w			al_worldz,y
	sec
	sbc			player_posz
	lbmi			.find	

	cmp			tpa
	a8
	lbmi			.find	

	s_set_alvartobeobj	x,al_sword1,y
	s_set_alsflag		y,lockon
	s_set_alvar			B,y,al_openal,#3

.skipfind
	s_jmp_notdelay		2,.found
	s_weapon_pos		#0,#0,#80
	s_weapon_rot		#0,#0
	phy
	s_fire_weapon		x,ELASER
	ply
;	inc	teamshots
;	lda	teamshots
;	cmp	#60
;	lbpl	.end
	s_brl			.found
.nofind

	inc	testforassault
	lda	testforassault
	cmp	#9
	beq	.6
	bra	.3
.6
	s_jmp			assault1_strat.dofind2

.3		;exit
	s_jmp			assaultall_strat.dofind2
	s_achase_alvar		B,x,al_roty,#0,5
	s_achase_alvar		B,x,al_rotx,#0,5

	s_achase_alvar		W,x,al_worldx,playeronex,5
	s_achase_alvar		W,x,al_worldy,playeroney,5


	s_brl			.cont

.found
;	s_set_alsflag		y,hitflash
	s_obj2obj_3dangle	x,y,al_roty,al_rotx,3

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarless		W,x,al_worldy,maxpmoveY,.nfpbottom	;
	s_set_alvar		W,x,al_worldy,maxpmoveY					;

	s_test_var		B,pmovelimitAND,#pml_Bbottom			;
	s_bne			.nfpbottom								;
	s_or_var		B,arrows,#sprar_down					;
	s_sub_alvar		W,x,al_worldy,#5
	bra	.top
.nfpbottom													;limit up and down movement
													;
;	s_jmp_alvarlessEQ		W,x,al_worldy,maxpmoveY-10,.change
;	bra	.top
;.change
;	s_achase_alvar		B,x,al_rotx,#0,1															;
	
.top
	s_jmp_alvarmore		W,x,al_worldy,minpmoveY,.nfptop		;
	s_set_alvar		W,x,al_worldy,minpmoveY					;
	s_or_var		B,arrows,#sprar_up						;
;	s_add_alvar		W,x,al_worldy,#5
.nfptop														;

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarmore	W,x,al_worldX,minpmoveX,.nminX
	s_set_alvar	W,x,al_worldX,minpmoveX
	s_or_var		B,arrows,#sprar_left
	s_add_alvar		W,x,al_worldx,#5
.nminX
	s_jmp_alvarless	W,x,al_worldX,maxpmoveX,.nmaxX
	s_set_alvar	W,x,al_worldX,maxpmoveX						;limit left/right movement
	s_or_var		B,arrows,#sprar_right
	s_sub_alvar		W,x,al_worldx,#5
.nmaxX
;-----------------------------------------------------------------------------------
.cont

	LDA	AL_ROTY,X
	ASL	A
	ASL	A
	STA	AL_ROTZ,X
	
	s_end_strat

.end

;	stz	teamshots
	stz	teamon
	s_remove_offscn	x

	s_set_path		x,flyawayplease
	
.endrem	
	s_set_strat		x,0
	s_end_strat

	
assaultall_strat
.dofind2	LOCAL
	s_set_alvar		W,x,al_sword1,#0

.dofind	s_set_find		0
.find	
	s_find_radiusobj	y,x,#0,#0,#3000,.nofind
;	s_jmp_alsflag		y,lockon,.find
;	s_jmpNOT_colltype	y,Zenemy,.find
	s_jmp_colltype	y,friend,.find
	s_jmp_colltype	y,laser,.find
	s_jmp_alsflag		y,nohitaffect,.find
	s_jmp_alsflag		y,colldisable,.find
	s_jmp_alvarEQ.w		B,y,al_hp,#hardHP,.find
	a16
	lda.w			al_worldx,y
	sec
	sbc			playeronex
	bpl			.nneg
	nega
.nneg
	sta			tpa
	
	lda.w			al_worldz,y
	sec
	sbc			player_posz
	lbmi			.find	

	cmp			tpa
	a8
	lbmi			.find	

	s_set_alvartobeobj	x,al_sword1,y
	s_set_alsflag		y,lockon
	lda	#1
	sta	testforassault

.skipfind
	s_jmp_notdelay		2,.found
	s_weapon_pos		#0,#0,#80
	s_weapon_rot		#0,#0
	phy
	s_fire_weapon		x,ELASER
	ply
;	inc	teamshots
;	lda	teamshots
;	cmp	#60
;	lbpl	.end
	s_brl			.found
.nofind
	inc	testforassault
	lda			testforassault
	cmp	#1
	beq	.1
	bra	.7
.1
	s_jmp			assault2_strat.dofind2
.7		;exit

	s_achase_alvar		B,x,al_roty,#0,5
	s_achase_alvar		B,x,al_rotx,#0,5

	s_achase_alvar		W,x,al_worldx,playeronex,5
	s_achase_alvar		W,x,al_worldy,playeroney,5


	s_brl			.cont

.found
;	s_set_alsflag		y,hitflash
	s_obj2obj_3dangle	x,y,al_roty,al_rotx,3

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarless		W,x,al_worldy,maxpmoveY,.nfpbottom	;
	s_set_alvar		W,x,al_worldy,maxpmoveY					;

	s_test_var		B,pmovelimitAND,#pml_Bbottom			;
	s_bne			.nfpbottom								;
	s_or_var		B,arrows,#sprar_down					;
	s_sub_alvar		W,x,al_worldy,#5
	bra	.top
.nfpbottom													;limit up and down movement
													;
;	s_jmp_alvarlessEQ		W,x,al_worldy,maxpmoveY-10,.change
;	bra	.top
;.change
;	s_achase_alvar		B,x,al_rotx,#0,1															;
	
.top
	s_jmp_alvarmore		W,x,al_worldy,minpmoveY,.nfptop		;
	s_set_alvar		W,x,al_worldy,minpmoveY					;
	s_or_var		B,arrows,#sprar_up						;
;	s_add_alvar		W,x,al_worldy,#5
.nfptop														;

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	s_jmp_alvarmore	W,x,al_worldX,minpmoveX,.nminX
	s_set_alvar	W,x,al_worldX,minpmoveX
	s_or_var		B,arrows,#sprar_left
	s_add_alvar		W,x,al_worldx,#5
.nminX
	s_jmp_alvarless	W,x,al_worldX,maxpmoveX,.nmaxX
	s_set_alvar	W,x,al_worldX,maxpmoveX						;limit left/right movement
	s_or_var		B,arrows,#sprar_right
	s_sub_alvar		W,x,al_worldx,#5
.nmaxX
;-----------------------------------------------------------------------------------
.cont

	LDA	AL_ROTY,X
	ASL	A
	ASL	A
	STA	AL_ROTZ,X
	
	s_end_strat

.end

;	stz	teamshots
	stz	teamon
	s_remove_offscn	x

	s_set_path		x,flyawayplease
	
.endrem	
	s_set_strat		x,0
	s_end_strat


nomorep2
	lda	#0
	sta	twoplayer
	lda	#1
	sta	dohofs
	lda	#1
	sta	dovofs
	stz	noxrot
	stz	playertwoactivated
	s_playerfly_mode	planet
	lda	shpmode
	beq	.normdist
	s_set_var    W,viewdist,#160
	s_set_var    W,outviewdist,#160
	s_set_var    W,outdist,#160
	bra	.donedist
.normdist
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120
.donedist
	stz	viewtype
	lda	#0
	sta.l	m_damagetwo
	stz	speccnttwo
	s_remove_obj	x
	s_end_strat
	

activatesecondplayer_l
	jsr	activatesecondplayer
	rtl
	
activatesecondplayer
	stz	playertwoready
	s_set_var		B,firedelaytwo,#1
	s_set_var		B,specialdelaytwo,#1	
	s_set_var		B,firedelaythree,#1
	s_set_var		B,specialdelaythree,#1	
	s_set_var		B,firedelayfour,#1
	s_set_var		B,specialdelayfour,#1	
	s_set_var		B,firedelayfive,#1
	s_set_var		B,specialdelayfive,#1	
	stz	debugalien
	s_set_var		B,viewtype,#viewtype_twop ;!viewtype_toobj
	s_or_var	B,gameflags,#gf_viewrot
	s_copy_var2var	W,speccnttwo,specwepcnttootemp
	s_copy_var2var	W,speccntthree,specwepcntthreetemp
	s_copy_var2var	W,speccntfour,specwepcntfourtemp
	s_copy_var2var	W,speccntfive,specwepcntfivetemp
	lda	#1
	sta	twoplayer

	s_set_var	W,viewdist,#400
	s_set_var	W,outviewdist,#400
	s_set_var	W,outdist,#400

	stz	dovofs			;Disable tilt in 2p mode
	stz	dohofs			;Disable BG scrolling left/right

	a8
	lda	multitapmode
	lbne	.multitap

	lda	playertwocpuactivated
	cmp	#1
	lbeq	.cpu
	cmp	#2
	lbeq	.cpuplus
	cmp	#3
	lbeq	.assault
	lda	shpmode
	beq	.n1
	s_make_obj		#player2shparwing,.finishedthanks1
	s_set_strat		y,twoplayer_Istrat	
	sty		playpttwo
	jmp	.finishedthanks1
.n1
; PLAYER 2 SHIP SELECT FIX - PART 1
; Sunlit and Monika were here - August 8, 2024
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	lda	curr_ship2
	beq	.normalp2shp
	a16
	lda	curr_ship2							;load current ship number
	asl	a									;multiply by 2 (each ship takes up 2 slots)
	phx
	tax										;transfer to X
	lda.l	shiplistshape,x			
	plx
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
	jmp	.donep2case1
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
.normalp2shp
	s_make_obj		#playertwo1,.finishedthanks1
.donep2case1

	s_set_strat		y,twoplayer_Istrat
	sty		playpttwo
	jmp	.finishedthanks1
.cpu
	lda	shpmode
	beq	.n2
	s_make_obj		#player2shparwing,.finishedthanks1
	s_set_strat		y,twoplayercpu_Istrat	
	sty		playpttwo
	jmp	.finishedthanks1
.n2
	s_make_obj		#playertwo1,.finishedthanks1
	s_set_strat		y,twoplayercpu_Istrat	
	sty		playpttwo
	jmp	.finishedthanks1
.cpuplus
	lda	shpmode
	beq	.n3
	s_make_obj		#player2shparwing,.finishedthanks1
	s_set_strat		y,frienderaser_Istrat	
	sty		playpttwo
	jmp	.finishedthanks1

.n3
	s_make_obj		#playertwo1,.finishedthanks1
	s_set_strat		y,frienderaser_Istrat	
	sty		playpttwo
	jmp	.finishedthanks1

.assault
	lda	shpmode
	beq	.normships
	s_make_obj		#peppyshparwing,.finishedthanks1
	s_set_strat		y,assault1_Istrat
	s_make_obj		#falcoshparwing,.finishedthanks1
	s_set_strat		y,assault2_Istrat
	s_make_obj		#slippyshparwing,.finishedthanks1
	s_set_strat		y,assault3_Istrat
	jmp	.finishedthanks1
.normships
	s_make_obj		#peppy1,.finishedthanks1
	s_set_strat		y,assault1_Istrat
	s_make_obj		#falco1,.finishedthanks1
	s_set_strat		y,assault2_Istrat
	s_make_obj		#slippy1,.finishedthanks1
	s_set_strat		y,assault3_Istrat
	jmp	.finishedthanks1
	
.multitap
	
.2
	lda	curr_ship2
	beq	.reg2
	a16
	lda	curr_ship2							;load current ship number
	asl	a									;multiply by 2 (each ship takes up 2 slots)
	phx
	tax										;transfer to X
	lda.l	shiplistshape,x			
	plx
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
	jmp	.cont2
.reg2
	a16
	lda	#peppy1
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
.cont2
	s_set_strat		y,twoplayer_istrat
	sty		playpttwo
	a8
	lda	#1
	sta.l	m_playertwo
	lda	numplayers
	cmp	#1
	beq	.3
	cmp	#3
	lbmi	.finishedthanks1
;	jmp	.finishedthanks1

.3
	lda	curr_ship3
	beq	.reg3
	a16
	lda	curr_ship3							;load current ship number
	asl	a									;multiply by 2 (each ship takes up 2 slots)
	phx
	tax										;transfer to X
	lda.l	shiplistshape,x			
	plx
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
	jmp	.cont3
.reg3
	a16
	lda	#falco1
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
.cont3
	s_set_strat		y,thirdplayer_istrat
	sty		playptthree
	a8
	lda	#1
	sta.l	m_playerthree
	lda	numplayers
	cmp	#1
	beq	.4
	cmp	#4
	lbmi	.finishedthanks1


.4
	lda	curr_ship4
	beq	.reg4
	a16
	lda	curr_ship4							;load current ship number
	asl	a									;multiply by 2 (each ship takes up 2 slots)
	phx
	tax										;transfer to X
	lda.l	shiplistshape,x			
	plx
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
	jmp	.cont4
.reg4
	a16
	lda	#slippy1
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
.cont4
	s_set_strat		y,fourthplayer_istrat
	sty		playptfour
	a8
	lda	#1
	sta.l	m_playerfour
	lda	numplayers
	cmp	#1
	beq	.5
	cmp	#5
	lbmi	.finishedthanks1


.5
	lda	curr_ship5
	beq	.reg5
	a16
	lda	curr_ship5							;load current ship number
	asl	a									;multiply by 2 (each ship takes up 2 slots)
	phx
	tax										;transfer to X
	lda.l	shiplistshape,x			
	plx
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
	jmp	.cont5
.reg5
	a16
	lda	#playertwo1
	sta	tpa
	a8
	jsl	sr_make_obj
;	rlbcc	.finishedthanks1
.cont5
	s_set_strat		y,fifthplayer_istrat
	sty		playptfive
	a8
	lda	#1
	sta.l	m_playerfive

.finishedthanks1
	lda	whichroute
	cmp	#1
	bne	.no
	lda	stage
	cmp	#5
	bne	.no
	jsl	doascene
	
.no
	rts

doascene
;	s_set_var		B,viewtype,#viewtype_norm
	stz	viewtype
	s_and_var	B,gameflags,#~gf_viewrot	
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120
	lda	#1
	sta	dovofs
	sta	dohofs
	rtl
	
scenedone
	s_set_var		B,viewtype,#viewtype_twop
	s_or_var	B,gameflags,#gf_viewrot	
	s_set_var    W,viewdist,#400
	s_set_var    W,outviewdist,#400
	s_set_var    W,outdist,#400
	stz	dovofs
	stz	dohofs
	rtl


checkview_l
	lda	playertwoactivated
	bne	.noimdone3pointer
	lda	superspeeddelay
	cmp	#ktest
	beq	.noimdone3pointer
	cmp	#ktest3
	beq	.noimdone3pointer
	cmp	#ktest4
	beq	.noimdone3pointer
	cmp	#ktest5
	beq	.noimdone3pointer
	a16
	lda	cockpitmode
	bne	.cockpit
.force	LOCAL
;	a8
;	lda	superspeeddelay
;	eor	#ktest
;	sta	superspeeddelay
;	jsl	changeviewmode_l
;	a16
	a8
	lda	splayerflymode
	and	#spfm_inside
	beq	.noout
	s_and_var	B,superspeeddelay,#~ktest
	jsl	set_playeroutofcock_l
	lda	#255
	sta	crosshairon
	lda	#0
	sta	hudrot+1	; Off
.noout
	a16
	lda	curr_ship	; index into shiplistshape table
	cmp	#7	;skyb
	bmi	.maybe
	cmp	#77	;slippy1
	bmi	.maybe
	cmp	#78	;falco1
	bpl	.maybe
	cmp	#79	;peppy1
	bmi	.maybe
	cmp #24 ;plane1
	bmi	.maybe25
	cmp #40	;wolf
	bpl	.maybe25
	bra	.normdist
.noimdone3pointer
	jmp	.noimdone3
.cockpit
	a8
	stz	cockpitmode
	lda	shipbackup
	sta	curr_ship
	jsl	select_ship_l

	bra	.force
.maybe25
	a8
	s_set_var    W,viewdist,#300
	s_set_var    W,outviewdist,#300
	s_set_var    W,outdist,#300
	bra	.noimdone3
.maybe
	a8
	lda	shpmode
	beq	.normdist
	s_set_var    W,viewdist,#160
	s_set_var    W,outviewdist,#160
	s_set_var    W,outdist,#160
	bra	.donedist
.normdist
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120
.donedist
.noimdone3
	rtl
	
clearallobj
	s_set_find		0
.altfind
	s_find_obj		y,x,#0,.donefind	;find all the things!
	s_remove_obj	y
	bra	.altfind
.donefind
	rtl


checkview2_l
	lda	playertwoactivated
	bne	.noimdone3pointer
	lda	superspeeddelay
	cmp	#ktest
	beq	.noimdone3pointer
	cmp	#ktest3
	beq	.noimdone3pointer
	cmp	#ktest4
	beq	.noimdone3pointer
	cmp	#ktest5
	beq	.noimdone3pointer
	a16
	lda	cockpitmode
	bne	.cockpit
.force	LOCAL
	lda	curr_ship
	cmp	#7
	bmi	.maybe
	bra	.maybe25
.noimdone3pointer
	jmp	.noimdone3
.cockpit
	a8
	s_set_var    W,viewdist,#30
	s_set_var    W,outviewdist,#30
	s_set_var    W,outdist,#30
	bra	.noimdone3
.maybe25
	a8
	s_set_var    W,viewdist,#300
	s_set_var    W,outviewdist,#300
	s_set_var    W,outdist,#300
	bra	.noimdone3
.maybe
	a8
	lda	shpmode
	beq	.normdist
	s_set_var    W,viewdist,#160
	s_set_var    W,outviewdist,#160
	s_set_var    W,outdist,#160
	bra	.donedist
.normdist
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120
.donedist
.noimdone3
	rtl
	
setship			;main routine to set the ships model
	a8
	lda	curr_ship
	sta	temp_ship
	lbeq	.norm
.backtonorm	
	lda	curr_ship
	asl	a
	sta	tempshipname
	ldx	playpt
	s_copy_var2alvar		B,x,al_sbyte3,tempshipname
	s_set_alvar2alvartab	B,W,W,x,al_shape,x,al_sbyte3,shiplistshape		;stored in continue.asm
	bra	.donewithit
	
.norm
	lda	shpmode
	beq	.backtonorm
	s_set_alvar		W,x,al_shape,#P1SHPARWING		;super high poly
;	bra	.donewithit
	
.donewithit
	rtl	
	
setship2			;main routine to set the ships model
	a8
	lda	curr_ship
	lbeq	.norm
.backtonorm	
	lda	curr_ship
	asl	a
	sta	tempshipname
	s_copy_var2alvar		B,x,al_sbyte3,tempshipname
	s_set_alvar2alvartab	B,W,W,x,al_shape,x,al_sbyte3,shiplistshape		;stored in continue.asm
	rtl
	
.norm
	lda	shpmode
	beq	.backtonorm
	s_set_alvar		W,x,al_shape,#P1SHPARWING		;super high poly
	rtl	
	
	
PLWbrk_Istrat
	s_start_strat
	s_jmp_varAND	B,pshipflags3,#psf3_nocollisions,.donee	
	TRIGSE			se_wingdestructleft
	s_set_alvar		B,x,al_HP,#-1
	s_set_alvar		B,x,al_AP,#0
	s_and_var		B,pshipflags,#~psf_Lwingcoll
	s_or_var		B,pshipflags,#psf_brkLwing
	lda	curr_ship
	beq	.change			;if set to 0, change to left wing break
	cmp	#shipcount+2				;if right wing break already 
	beq	.changeb		;change to both broken
	bra	.nochange		;otherwise, do nothing
.change
	lda	#shipcount+1				;left wing break
	sta	curr_ship
	jsl	setship
	bra	.nochange
.changeb
	lda	#shipcount+3				;both broken
	sta	curr_ship
	jsl	setship
	bra	.nochange

.nochange
	ldy			pcboxobj_B
	s_set_alvar		B,y,al_collcount,#framesperAP
	s_jsl			makesmlexpobj_srou 
	s_set_alvar		W,y,al_vz,pviewvelz
.donee
	s_jmpto_strat		

;----------------------


;*****************************************************************************
playercoll_Istrat
	s_start_strat

	s_jmp_varAND	B,pshipflags3,#psf3_nocollisions,.ncoll
	
	s_inc_var		B,pnumhits 

	s_jmpNOT_varAND		B,pshipflags2,#psf2_wireship,.normcoll
	TRIGSE			$14
	s_set_objtobealvar	y,x,al_collobjptr
	s_jmp_alvarNE.w		B,y,al_hp,#hardHP,.ncoll
.normcoll

	s_jmp_alsflag		x,nohitaffect,.ncoll

	IFEQ	1
;KERT G STUFF
	phx
	ldx	pcboxobj_B
	lda.l			al_hp,x
	cmp	#30
	bpl	.no
	s_add_alvar			B,x,al_hp,#20
.no	
	plx
;END KERT G STUFF
	ENDC
;-----------------------------------------
; laser deflection.
	s_jmp_varZERO		B,player_rollZvel,.nlaser
	s_set_objtobealvar	y,x,al_collobjptr
	s_jmpNOT_colltype	y,laser,.nlaser
	s_jmp_alvarEQ.w		B,y,al_hp,#HARDHP,.nlaser
	phx
	tyx

	s_set_alvar2rnd		x,al_rotx,#63
	s_sub_alvar		B,x,al_rotx,#31
	s_set_speed		x,#60
	s_set_alvar2rnd		x,al_roty,#31
	s_jmp_random		.left
	s_sub_alvar		B,x,al_roty,#deg90-40
	s_brl			.contdef
.left	s_add_alvar		B,x,al_roty,#deg90-40
.contdef      
	s_gen_3dvecs		x,al_roty,al_rotx,al_speed
	s_add_vecs2pos		x
	s_add_vecs2pos		x
	s_add_vecs2pos		x
	s_add_vecs2pos		x
	s_clr_alsflag		x,collide
	s_set_alsflag		x,colldisable
	s_set_strat			x,relflatmiss_strat
	s_set_lifecnt		x,#30
	trigse			$14
	plx
	s_jmp			.ncoll
.nlaser
;-----------------------------------------
 
	s_jmpNOT_alvarAND	B,x,al_hitflags,#HF1,.nBcol
	ldy			pcboxobj_B
	s_set_alsflag		y,collide
	s_set_alsflag		y,hitflash
	s_copy_alvar2alvar.w	W,y,al_collobjptr,x,al_collobjptr
.nBcol	

	s_jmpNOT_alvarAND	B,x,al_hitflags,#HF2,.nLWcol
	ldy			pcboxobj_LW
	s_set_alsflag		y,collide
	s_set_alsflag		y,hitflash
	s_copy_alvar2alvar.w	W,y,al_collobjptr,x,al_collobjptr
.nLWcol	

	s_jmpNOT_alvarAND	B,x,al_hitflags,#HF3,.nRWcol
	ldy			pcboxobj_RW
	s_set_alsflag		y,collide
	s_set_alsflag		y,hitflash
	s_copy_alvar2alvar.w	W,y,al_collobjptr,x,al_collobjptr
.nRWcol	


.ncoll
	
	s_set_alvar		B,x,al_hitflags,#0
	s_clr_alsflag		x,collide

	s_jmpto_strat


;*****************************************************************************
calcteamdamage_l

	a8
	lda	specialobjtotal
	clc
	adc	spectot
	sta	spectot
	lda	specials_dead
	clc
	adc	spectotdead
	sta	spectotdead
	s_and_var	B,superspeeddelay,#~ktest
	s_and_var	B,superspeeddelay,#~ktest2
	s_and_var	B,superspeeddelay,#~ktest3
	s_and_var	B,superspeeddelay,#~ktest4	
	s_and_var	B,superspeeddelay,#~ktest5	
	a8
	lda	specialobjtotal
	sec
	sbc	specials_dead
	beq	.plok
	asl	a
	sta	tpa
	lda	planetdead
	clc
	adc	tpa
	cmp	#100
	bcc	.plok2
	lda	#100
.plok2	sta	planetdead
.plok
	rtl

	strats_end


;*****************************************************************************
calcbgscroll_l
	phy
	php
	i8
	

	a16
	lda		outvx
	asra
	asra
	asra
	asra
	asra
	asra
	sta	tpa
	asra
	clc
	adc	tpa
	nega

	ldy	nomaxbg2Yscroll
	bne	.nmin

	cmp	#232
	bmi	.nmax
	lda	#232
.nmax

	cmp	#-56
	bpl	.nmin
	lda	#-56
.nmin

	clc
	adc		bg2Yscroll
	and		#511
	sta		bg2scroll
	stz		lastrot

	lda		outvy
	sec
	sbc		player_turnrot
	asra	
	asra	
	asra	
	asra	
	asra
	clc
	adc		bg2Xscroll
	sta.l		m_scrollxoff
	a8

	plp
	ply
	rtl
	
;*****************************************************************************
pBody_Istrat
	s_start_strat
	s_setnoremove_behind	x
	s_set_alptrs		x,pBody_strat,pcolB_Istrat,pcolBexp_Istrat
	s_set_aldata		x,playerb_hp,#playerB_AP
	s_set_vartobeobj	pcboxobj_B,x
	s_and_var		B,pshipflags,#~psf_bodycoll
	s_set_alsflag		x,colldisable
	s_end_strat
pBody_strat
	s_start_strat
	s_set_objtobeplayer	y
	s_copy_pos		x,y	
	s_copy_rots		x,y	
	s_add_Roffs2pos		B,x,x,x,#0,#0,#0,0,0,1
;	d_print_alvar		B,x,al_HP,2

;	s_jmp_alvarmore	W,x,al_worldy,minpmoveY,.nminy
;	s_or_var	B,pmovelimit,#pml_btop
;.nminy

;	s_jmp_alvarless	W,x,al_worldy,maxpmoveY,.nmaxy
;	s_or_var	B,pmovelimit,#pml_bbottom
;.nmaxy

	s_end_strat

pBody2_Istrat
	s_start_strat
	s_setnoremove_behind	x
	s_set_alptrs		x,pBody2_strat,pcolB_Istrat,pcolBexp_Istrat
	s_set_aldata		x,playerb_hp,#playerB_AP
	s_set_vartobeobj	pcboxobj_B,x
	s_and_var		B,pshipflags,#~psf_bodycoll
	s_set_alsflag		x,colldisable
pBody2_strat
	s_start_strat
	s_set_objtobeplayer	y
;	s_copy_pos		x,y	
	s_copy_rots		x,y	
	s_add_Roffs2pos		B,x,x,x,#0,#0,#0,0,0,1
;	d_print_alvar		B,x,al_HP,2

	s_jmp_alvarmore	W,x,al_worldy,minpmoveY,.nminy
	s_or_var	B,pmovelimit,#pml_btop
.nminy

	s_jmp_alvarless	W,x,al_worldy,maxpmoveY,.nmaxy
	s_or_var	B,pmovelimit,#pml_bbottom
.nmaxy
	s_add_playerz		x
	s_end_strat


;-------------------------------------------------------------------------------
changeviewmode_l

;this code checks for and turns off cockpit mode or isometric view and goes back to normal view
	lda	cockpitmode
	beq	.checkisoview
	bra	.turnoffcock
.checkisoview
	lda	isoviewmode
	beq	.turnoffcock
	bne	.turnoffisoview
	jmp	.nocockpit

.turnoffcock
	stz	cockpitmode	;turn off cockpit mode
	s_jmpNOT_varAND    B,superspeeddelay,#ktest,.nocockpit
;	stz	curr_ship
	stz	shiptemp
.turnoffisoview
	stz	isoviewmode
	jsl	set_playeroutofcock_l
	lda	shpmode
	beq	.normaldist
	s_set_var    W,viewdist,#160
	s_set_var    W,outviewdist,#160
	s_set_var    W,outdist,#160	
	bra	.donedist
.normaldist
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120	
.donedist
	s_set_var	W,outvx,#0
	s_set_var	W,outvy,#0
	s_and_var	B,superspeeddelay,#~ktest
	s_and_var	B,superspeeddelay,#~ktest2
	s_and_var	B,superspeeddelay,#~ktest3
	s_and_var	B,superspeeddelay,#~ktest4
	s_and_var	B,superspeeddelay,#~ktest5
	s_and_var	B,crosshairflag,#~crosshairoff
	lda	#255
	sta	crosshairon
	lda	#0
	sta	hudrot+1	; Off
	jsl	checkview2_l
	jmp	.ntoinside
;-----now that thats done, here's the rest to go into cockpit mode

.nocockpit				;go into cockpit mode
	s_jmp_varAND    B,superspeeddelay,#ktest,.ntoinside
.changein
	lda	frozen
	lbne	.ntoinside
	s_and_var		B,gameflags,#~gf_nozremove	
	s_set_var	W,outvx,#0
	s_set_var	W,outvy,#0
	s_set_var	B,splayerflymode,#spfm_inside
	lda	#-1
	sta	hudrot+1	; ON
	s_and_var	B,crosshairflag,#~crosshairoff
	s_or_var	B,superspeeddelay,#ktest
	s_and_var	B,superspeeddelay,#~ktest2
	lda	#255
	sta	crosshairon
	s_set_alsflag	x,invisible
	jsl	set_playerintocock_l
	stz	isoviewmode
	jmp		.ntoinside
	
;.nnorm
;	a16
;	lda	curr_ship
;	cmp	#19
;	bmi	.less2
;	s_set_var    W,viewdist,#200
;	s_set_var    W,outviewdist,#200
;	s_set_var    W,outdist,#200
;	bra	.more2
;.less2
;	s_set_var    W,viewdist,#120
;	s_set_var    W,outviewdist,#120
;	s_set_var    W,outdist,#120
;.more2
;	s_set_var	W,outvx,#0
;	s_set_var	W,outvy,#0
;	s_set_var	B,splayerflymode,#spfm_norm
;	lda	#0
;	sta	hudrot+1
;	s_and_var	B,crosshairflag,#~crosshairoff
;	s_and_var		B,gameflags,#~gf_nozremove	
;	s_and_var    B,superspeeddelay,#~ktest
;	s_or_var	B,superspeeddelay,#ktest2
;	lda	#255
;	sta	crosshairon
;	lda	frozen
;	lbne	.ntoinside
;	jsl	set_playeroutofcock_l
;	jmp		.ntoinside

	
;.nnorm4
;	s_set_var	W,viewdist,#300
;	s_set_var	W,outviewdist,#300
;	s_set_var	W,outdist,#300
;	s_set_var	W,outvx,#0
;	s_set_var	W,outvy,#0
;	s_or_var	B,crosshairflag,#crosshairoff
;	s_and_var	B,gameflags,#~gf_nozremove	
;	stz			crosshairon
;	s_and_var	B,superspeeddelay,#~ktest
;	s_and_var	B,superspeeddelay,#~ktest2
;	s_or_var	B,superspeeddelay,#ktest5
;	stz	isoviewmode
;	jmp		.ntoinside
	
;.nnorm5
;	lda	frozen
;	lbne	.nnorm
;	a16
;	lda	cockpitmode
;	bne	.cockpit25
;	lda	curr_ship
;
;	cmp	#19
;	bmi	.less3

;	s_set_var    W,viewdist,#200
;	s_set_var    W,outviewdist,#200
;	s_set_var    W,outdist,#200
;	bra	.more3
;.cockpit25
;	s_set_var    W,viewdist,#30
;	s_set_var    W,outviewdist,#30
;	s_set_var    W,outdist,#30
;	bra	.more3

.less3
;	s_set_var    W,viewdist,#120
;	s_set_var    W,outviewdist,#120
;	s_set_var    W,outdist,#120
.more3
;	s_set_var	W,outvx,#0
;	s_set_var	W,outvy,#0
;	s_and_var	B,crosshairflag,#~crosshairoff
;	s_and_var		B,gameflags,#~gf_nozremove	
;	s_and_var    B,superspeeddelay,#~ktest
;	s_and_var	B,superspeeddelay,#~ktest2
;	s_and_var    B,superspeeddelay,#~ktest3
;	s_and_var    B,superspeeddelay,#~ktest4
;	s_and_var	B,superspeeddelay,#~ktest5
;	stz	isoviewmode
;	lda	#1
;;	sta	cockpitmode
;	lda	#255
;	sta	crosshairon
;	jsl	set_playeroutofcock_l
.ntoinside
	rtl

;-------------------------------------------------------------------------------


framescalevecs
	phb
	IFNE	FASTROM
	lda	#$80
	pha
	plb
	ELSEIF
	lda	#0
	pha
	plb
	ENDC

	lda	al_vx,x
	sta	x1+1
	stz	x1	
	lda	al_vy,x
	sta	y1+1
	stz	y1	

	
	lda	framerate
	sta	tpx

	phx
	i8

	mulslog168 x1,tpx
	lda m4
	sta	x1
	lda m5
	sta	x1+1
	mulslog168 y1,tpx
	lda m4
	sta	y1
	lda m5
	sta	y1+1

	ai16
	plx

	
	lda	x1
	adiv2			; 1 for mult.
	adiv2
	adiv2
	sta	al_vx,x
	lda	y1
	adiv2			; 1 for mult
	adiv2
	adiv2
	sta	al_vy,x
	
	a8
	plb
	rtl

resettheview
	s_and_var		B,gameflags,#~gf_nozremove
    s_set_var        W,player_turnrot,#0
	jsl				playerstraight_strat
	stz		frozen
;	s_or_var		B,pshipflags3,#psf3_nocollisions
	lda	#0
	sta	nolockview
	s_set_var	W,outvx,#0
	s_set_var	W,outvy,#0
	s_set_var	W,outvz,#0
	rtl

gameoverinit_l

	a8i16
	phx
	lda	#waitmap>>16
	sta	mapbank
	ldx	#waitmap&7fffh
	stx	mapptr
	plx

	jsl	initgame_l
	jsl	playerstart_init_l
	jsl	set_playercred_l

	lda	#0
	sta.l	m_particlesON
	sta.l	m_particlesON+1

	lda	gameflags
	and	#~gf_playerdying
	sta	gameflags

	ldx	playpt
	a8i16
	s_make_obj		#gamesh,.nob
	s_set_strat		y,path_istrat
	s_set_path		y,gameover
	s_set_aldata	y,#255,#0
	s_copy_pos		y,x
	s_set_alvar		W,y,al_worldx,#-270
	s_add_alvar		W,y,al_worldy,#120
	s_add_alvar		W,y,al_worldz,#3400	;800
.nob
	s_make_obj		#oversh,.nober
	s_set_strat		y,path_istrat
	s_set_path		y,gameover
	s_set_aldata	y,#255,#0
	s_copy_pos		y,x
	s_set_alvar		W,y,al_worldx,#270
	s_add_alvar		W,y,al_worldy,#120
	s_add_alvar		W,y,al_worldz,#3400	;800
.nober

	a16
	ldx	#0
.lp	stz	pal0palette,x
	inx
	inx
	cpx	#32*7
	bne	.lp

	txy
	ldx	#0
.lp2	lda.l	gameoverpal,x
	sta.w	pal0palette,y
	iny
	iny
	inx
	inx
	cpx	#32
	bne	.lp2

	lda	#-1
	sta	dotsflag

	lda	#0
	sta.l	m_meters

endgameoverinit
	rtl

boostl_Istrat	s_start_strat
	s_set_lifecnt	x,#10
	s_set_alsflag	x,colldisable
	s_set_strat	x,boostl_strat
	s_copy_alvar2var	B,x,svar_byte1,al_sbyte1
	s_sprite_obj	x,#0,svar_byte1
	s_clr_alsflag	x,invisible
	s_setnoremove_behind	x
boostl_strat
	s_start_strat
	s_dec_alvar		B,x,al_tx
	s_set_objtobevar	y,boostobj
	s_jmp_objptrbad		y,remove_Istrat
	s_add_Roffs2pos		B,x,y,y,#25,#0,boostZoff,1,1,1
	s_dec_lifecnt		x
	s_end_strat

boostr_Istrat	s_start_strat
	s_set_lifecnt	x,#10
	s_set_alsflag	x,colldisable
	s_set_strat	x,boostr_strat
	s_copy_alvar2var	B,x,svar_byte1,al_sbyte1
	s_sprite_obj	x,#0,svar_byte1
	s_clr_alsflag	x,invisible
	s_setnoremove_behind	x
boostr_strat
	s_start_strat
	s_dec_alvar		B,x,al_tx
	s_set_objtobevar	y,boostobj
	s_jmp_objptrbad		y,remove_Istrat
	s_add_Roffs2pos		B,x,y,y,#-25,#0,boostZoff,1,1,1
	s_dec_lifecnt		x
	s_end_strat	
	
boostl2_Istrat	s_start_strat
	s_set_lifecnt	x,#10
	s_set_alsflag	x,colldisable
	s_set_strat	x,boostl2_strat
	s_copy_alvar2var	B,x,svar_byte1,al_sbyte1
	s_sprite_obj	x,#0,svar_byte1
	s_clr_alsflag	x,invisible
	s_setnoremove_behind	x
boostl2_strat
	s_start_strat
	s_dec_alvar		B,x,al_tx
	s_set_objtobevar	y,boostobj
	s_jmp_objptrbad		y,remove_Istrat
	s_add_Roffs2pos		B,x,y,y,#14,#0,boostZoff,1,1,1
	s_dec_lifecnt		x
	s_end_strat

boostr2_Istrat	s_start_strat
	s_set_lifecnt	x,#10
	s_set_alsflag	x,colldisable
	s_set_strat	x,boostr2_strat
	s_copy_alvar2var	B,x,svar_byte1,al_sbyte1
	s_sprite_obj	x,#0,svar_byte1
	s_clr_alsflag	x,invisible
	s_setnoremove_behind	x
boostr2_strat
	s_start_strat
	s_dec_alvar		B,x,al_tx
	s_set_objtobevar	y,boostobj
	s_jmp_objptrbad		y,remove_Istrat
	s_add_Roffs2pos		B,x,y,y,#-14,#0,boostZoff,1,1,1
	s_dec_lifecnt		x
	s_end_strat
	
	

;*****************************************************************************
laserflash
	ifeq	1
	phx
	tyx
	
	s_set_objtobeplayer	y
	s_set_var		W,swvar_word1,#Sflash_0
	s_jmp_Zdistless		x,y,#bigSflashDist,.flashsize
	s_set_var		W,swvar_word1,#Mflash_0
	s_jmp_Zdistless		x,y,#bigMflashDist,.flashsize
	s_set_var		W,swvar_word1,#Lflash_0
.flashsize

	s_make_obj	swvar_word1,.badobj
	s_copy_pos	y,x
	s_set_alvar	B,y,al_roty,#deg180
	s_set_strat	y,flash_Istrat
.badobj	txy
	plx
	rts

flash_Istrat
	s_start_strat
	s_sprite_obj	x,#0
	s_set_alsflag	x,colldisable
	s_init_COLanim	x,#0
	s_set_strat	x,flash_strat
	s_add_playerZ	x
	s_end_strat	
flash_strat
	s_start_strat
	s_add_playerZ	x
	s_cmp_COLanim	x,#2
	s_beq		remove_Istrat
	s_add_COLanim	x,#1,#4
	endc
	s_end_strat

	






	


;*****************************************************************************
Xflytopos_l
	a16
	lda			svar_word3
	sec
	sbc			al_worldx,x
	a8
	bmi			.dec
	inc			al_sbyte3,x	
	bra			.end
.dec
	dec			al_sbyte3,x	
.end

	s_limit_alvar		B,x,al_sbyte3,-10,10

	s_add_alvars		B,x,al_rotz,x,al_sbyte3
	s_limit_alvar		B,x,al_rotz,-deg45,deg45

	lda			al_sbyte3,x
	a16
	sexa
	clc
	adc			al_worldx,x
	sta			al_worldx,x
	a8

	s_achase_alvar		W,x,al_worldx,svar_word3,7

.stop
	rtl
	
setYplayershape_l
	asl	a
	asl	a
	asl	a
	sta	smvar_byte1

	lda	pshipflags
	and	#psf_brkLwing!psf_brkRwing
	beq	.nps

	bit	#psf_brkLwing
	beq	.notlb	
	bit	#psf_brkRwing
	bne	.bps
	s_set_alvar2vartab	B,W,W,y,al_shape,smvar_byte1,player_shapes+2
	bra	.gps
.notlb
	s_set_alvar2vartab	B,W,W,y,al_shape,smvar_byte1,player_shapes+4
	bra	.gps
.bps
	s_set_alvar2vartab	B,W,W,y,al_shape,smvar_byte1,player_shapes+6
	bra	.gps
.nps
	s_set_alvar2vartab	B,W,W,y,al_shape,smvar_byte1,player_shapes
.gps
	rtl

godguncollide_Istrat
	s_start_strat
	s_set_objtobealvar	y,x,al_collobjptr
	lda	bossmode
	lbne	.skip
	s_cmp_alvar			W,y,al_shape,#sface_b
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#sface2_b
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#luigih
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#andross
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#androsscube
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#fireface_b
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#fireface1_b
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#face_0
	lbeq				.skip

	s_cmp_alvar			W,y,al_shape,#face_0_1
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#face_1
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#face_box
	lbeq				.skip

	s_cmp_alvar			W,y,al_shape,#myship_4
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#p1shparwing
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#ship_3
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#boss_F_1
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#boss_F_2
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#boss_F_3
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#boss_F_4
	lbeq				.skip
	s_cmp_alvar			W,y,al_shape,#boss_d_a
	lbeq				.skip
	s_jmp_alsflag		y,colldisable,.solidhit
	s_jmp_alsflag		y,nohitaffect,.solidhit
	s_jmp_alvarEQ.w		B,y,al_hp,#hardHP,.solidhit	
	s_jmp_colltype	y,friend,.skip
	s_jmp_colltype	y,laser,.skip

	bra	.nsolidhit

.solidhit
	lda	bossmode
	bne	.nsolidhit
	lda	weaponnumber
	cmp	#98
	beq	.nsolidhit
	s_set_expstrat	y,explode_istrat
	s_remove_obj		y
	bra	.skip
.nsolidhit
	s_set_expstrat	y,explode_istrat
	s_kill_obj		y
.skip
 	s_end_strat
;*****************************************************************************
playerstraight_strat
	s_start_strat
	stz			arrows
	s_set_var		B,viewtype,#viewtype_norm
	s_set_var		W,plrotx,#0
	s_set_var		W,plroty,#0
	s_set_var		W,plrotz,#0
;	s_achase_var	W,outvx,#0,3
;	s_achase_var	W,outvy,#0,3
	s_set_var		W,outvz,#0
	s_set_alvar		B,x,al_rotx,#0
	s_set_alvar		B,x,al_roty,#0
	s_set_alvar		B,x,al_rotz,#0
	s_set_var		B,viewshakeX,#0
	s_set_var		B,viewshakeY,#0
	s_set_var		B,viewshakeZ,#0
	s_set_var		W,viewfloatX,#0
	s_set_var		W,viewfloatY,#0
	s_set_var		W,pviewposZoff,#0

	s_set_var	W,pviewvelz,#medpspeed
	s_set_speed		x,#medpspeed

	s_gen_3dvecs		x,al_roty,al_rotx,al_speed
	s_add_vecs2pos		x

	s_set_alvar	W,x,al_worldx,#0
	s_set_alvar	W,x,al_worldy,viewcy
	s_set_var	W,pviewposx,#0
	s_set_var	W,pviewposy,viewcy
          	s_add_var	W,pviewposz,pviewvelz
	s_end_strat

setrandomX
	php
	plp
	rtl
	
dupchance
	php
	a16
	jsl	random_l
	and	#512
	cmp	#50
	bpl	.dupit
	plp
	rtl
.dupit
	s_make_obj	#nullshape,.done
	phx
	tyx
	jsl	makelavabubble_srou_l
	plx
.done
	plp
	rtl
	
checkgodmodecode
;-------God Mode Code
;	php								;Push processor Status (?)			;---;			|
;	phb								;Push data bank register (?)		;---;			|
	a8i16							;8 bit accumulator, 16 bit index	;---;			|
																		;---;
;	lda	#$7e						;Load $7E bank						;---;	
;	plb								;Pull data bank register			;---;
	lda	godtemp
	and	#gm1
	cmp	#gm1
	beq	.gm2
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	DOWN
	lbeq	.npst

	lda	godtemp
	ora	#gm1
	sta	godtemp
	jmp			.npst
.gm2 ;(R Press Up)
	lda	godtemp
	and	#gm2
	cmp	#gm2
	beq	.gm3
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	RIGHT
	lbeq	.npst

	lda	godtemp
	ora	#gm2
	sta	godtemp
	jmp			.npst

.gm3 ;(R Press Down)
	lda	godtemp
	and	#gm3
	cmp	#gm3
	beq	.gm4
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	DOWN
	lbeq	.npst

	lda	godtemp
	ora	#gm3
	sta	godtemp
	jmp			.npst
.gm4 ;(R Press Down)
	lda	godtemp
	and	#gm4
	cmp	#gm4
	beq	.gm5
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	RIGHT
	lbeq	.npst

	lda	godtemp
	ora	#gm4
	sta	godtemp
	jmp			.npst
.gm5 ;(R Press Left)
	lda	godtemp
	and	#gm5
	cmp	#gm5
	beq	.gm6
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	LEFT
	lbeq	.npst

	lda	godtemp
	ora	#gm5
	sta	godtemp
	jmp			.npst
.gm6 ;(R Press Right)
	lda	godtemp
	and	#gm6
	cmp	#gm6
	beq	.gm7
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	UP
	lbeq	.npst

	lda	godtemp
	ora	#gm6
	sta	godtemp
	jmp			.npst
.gm7 ;(R Press Left)
	lda	godtemp
	and	#gm7
	cmp	#gm7
	beq	.gm8
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	LEFT
	lbeq	.npst

	lda	godtemp
	ora	#gm7
	sta	godtemp
	jmp			.npst
.gm8 ;(R Press Right)
	lda	godtemp2
	and	#gm8
	cmp	#gm8
	beq	.gm9
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo

	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	B
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	UP
	lbeq	.npst

	lda	godtemp2
	ora	#gm8
	sta	godtemp2
	jmp			.npst
.gm9 ;(R Press B)
	lda	godtemp2
	and	#gm9
	cmp	#gm9
	beq	.gm10
	TESTKEYDOWN	A,cont0l
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	B
	lbeq	.npst

	lda	godtemp2
	ora	#gm9
	sta	godtemp2
	jmp			.npst
.gm10 ;(R Press A)
	lda	godtemp2
	and	#gm10
	cmp	#gm10
	beq	.gm11
	TESTKEYDOWN	LEFT
	lbne	.resetcombo
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo

	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	A,cont0l
	lbeq	.npst

	lda	godtemp2
	ora	#gm10
	sta	godtemp2
	jmp			.npst
.gm11 ;(R Press Start)
	lda	godtemp2
	and	#gm11
	cmp	#gm11
	beq	.gm12
	TESTKEYDOWN	RIGHT
	lbne	.resetcombo
	TESTKEYDOWN	UP
	lbne	.resetcombo
	TESTKEYDOWN	DOWN
	lbne	.resetcombo
	TESTKEYDOWN	LEFT
	lbne	.resetcombo

	TESTKEYDOWN	B
	lbne	.resetcombo
	TESTKEYDOWN	X,cont0l
	lbne	.resetcombo

	TESTKEYDOWN	START
	lbeq	.npst

	lda	godtemp2
	ora	#gm11
	sta	godtemp2
	lda	#1
	sta	godmode
	sta	secretgodmode
	trigse	88h
.gm12	
	bra	.noimdone20
.resetcombo
	lda	#0
	sta	godtemp2 ;reset flags
	sta	godtemp ;reset flags
.noimdone20
.npst
;	settext	0,0
;	a8

;	plb
;	plp
	rtl



;---------------------------------------------------------------------------
screenoff_l
	php
	a8i16
	stz	hdmaen
	lda	#$80
	sta	inidisp
	setinidisp1
	waitdma	150
	waitdma	140						;wait for it all to take effect
	plp
	rtl
	
;---------------------------------------------------------------------------------------------------------
fadepalto_l	ai16
	ldy	palnum
	bne	.do
	rtl
.do
	ldx	palfade
	ldy	palnum

	lda.l	seapal,x
	sta.w	pal0palette+4*32,y

	dec	palfade
	dec	palfade
	dec	palnum
	dec	palnum
	rtl


palgoto_l	a8
	lda	pshipflags2
	and	#psf2_playerHP0
	beq	.set1
	rtl
.set1
	lda	nobgmode
	beq	.set2
	rtl
.set2
	lda	fadepal
	bne	.fadeit
	rtl
.fadeit	dec	a
	sta	fadepal

	ai16
	ldx	palfrom
	ldy	palto
	lda	pallen
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	mist2col,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	mist2col,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	mist2col,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	rtl

palgoto2_l	a8
	lda	fadepaltit
	bne	.fadeit
	rtl
.fadeit		dec	a
	sta	fadepaltit

	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	mist2col,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	mist2col,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	mist2col,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#26
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl

fadered_l	php
	phy
	phx
	phb

	a8
	IFNE	FASTROM
	lda	#$80
	pha
	plb
	ELSEIF
	lda	#0
	pha
	plb
	ENDC

	
	ai16
	ldy	#0
	lda	#8*16
.lp
	pha
	lda.w	pal0palette,y
	and	#%111111111100000

	sta	tpx
	lda.w	pal0palette,y
	and	#%11111
	cmp	#3
	ja	.ok
	ora	#3
.ok
	asl	a
	cmp	#31
	bcc	.nsh
	lda	#31
.nsh	and	#%11111
	ora	tpx
	sta.w	pal0palette,y
	iny
	iny
	pla
	dec	a
	bne	.lp
.out
	lda	#0
	sta	pal0palette+6*32+30

	plb
	plx
	ply
	plp
	rtl

makeBG2black_l
	phx
	a8
	lda	#0
	ldx	#(7*32)-1
.clr	sta.w	pal0palette,x
	dex	
	bpl	.clr
	plx
    rtl

	
kill_list_l	php
	ai16
	stz	allst	;clear Alien list
	FmtFreeLst	alfreelst,alblks,number_al,al_size
	plp
	rtl



showview_l
	php
	jsl	marioshowview_l
	a8i16
	call_mario	mallrotzsort
	plp
	rtl

alienflags_l
	php
	phb
	a8
	lda	#$7e
	pha
	plb

	i16
	ldx	#m_drawlist&WM
	ldy	allst
.next

	a8
	test_alsflag		y,invisible
	lbne			.nextal
;	s_jmp_alsflag		y,invisible,.nextal
	phx
	lda	craymode
	lbeq	.nocube
	cmp	#1
	beq	.1
	cmp	#2
	beq	.2
	cmp	#3
	beq	.3
	cmp	#4
	beq	.4
	cmp	#5
	beq	.5
	cmp	#6
	lbeq	.nocube

.1
	a16
	tyx
	lda.l	al_shape,x
	cmp	#nullshape&wm
	lbeq	.nocube

	lda	#luigih&wm
	sta.l	al_shape,x
	jmp	.nocube
	
.2
	a16
	tyx
	lda.l	al_shape,x
	cmp	#nullshape&wm
	lbeq	.nocube

	lda	#kandrosscubee&wm
	sta.l	al_shape,x
	jmp	.nocube
	
.3
	a16
	tyx
	lda.l	al_shape,x
	cmp	#nullshape&wm
	lbeq	.nocube

	lda	#nullshape&wm
	sta.l	al_shape,x
	jmp	.nocube
	
.4
	ai16
	tyx
	lda.l	al_shape,x
	cmp	#nullshape&wm
	lbeq	.nocube

	lda	#smallballz&wm
	sta.l	al_shape,x
	jmp	.nocube

.5
	ai16
	tyx
	lda.l	al_shape,x
	cmp	#nullshape&wm
	lbeq	.nocube

.again
	jsl	random_l
	and	#1023
	beq	.again
	cmp	#shiptot+1		;final number of shapes
	bpl	.again
	asl	a
	tax
	s_jmp_notdelay	3,.nocube				;CRAY MODE 5 DELAY
	lda.l	shapeslist,x
	tyx
	sta.l	al_shape,x
	
	
	
.nocube
	a16
	plx
	
	lda.w	al_shape,y
	stx	tpa
	tax
	lda.l	sh_zmax,x
	ldx	tpa
	adc.l	dl_z,x
	bpl	.dontkill


; kill the alien if its z is behind the view
	a8
	lda.w	al_flags,y
	and	#~affrontpl
	sta.w	al_flags,y

	s_test_var	B,gameflags,#gf_nozremove
	bne	.dontkill	
;	s_jmp_varAND		B,gameflags,#gf_nozremove,.dontkill

	test_alcollflags	y,acf_firstframe
	bne	.dontkill
	lda.w	al_type,y
	and	#atzremove
	beq	.dontkill
	phx
	tyx
	ldy	_next,x
	jsl	removedeadal_l
	a16
	pla
	clc
	adc	#dl_sizeof
	tax
	tya
	bra	.killed

.next2
	jmp	.next
.dontkill	a16
	lda.l	dl_x,x
	bpl	.right
.left	lda.w	al_flags,y
	ora	#afinviewpl+afleftpl
	sta.w	al_flags,y
	bra	.cont
.right	lda.w	al_flags,y
	ora	#afinviewpl
	sta.w	al_flags,y
.cont
	a16
	txa
	clc
	adc	#dl_sizeof
	tax

.nextal	a16
	lda.w	_next,y
.killed
	tay
	bne	.next2

	plb
	plp
	rtl
	
	
;-------------------------------------------------
;-------------------------------------------------
;-------------------------------------------------
; do animation for friends' text messages

; a = message to send
send_message_l
	php
	ai16
	and	#255
	dec	a
	cmp	#-1
	beq	.finished
	asl	a
	tax
	lda.l	messages,x
	tax
	a8
	lda.l	messages&~WM,x
	pha
	a16
	and	#127
	tay
	a8

;	lda.w	friends_hp-1,y
;	beq	.finished2

	lda	friends_meter
	inc	a
	bne	.nometer
	lda.w	friends_hp-1,y
	ora	#128
	sta	friends_meter
	bra	.meteron
	
.nometer	stz	friends_meter
.meteron
	pla
	sta	whichfriend

	inx
	lda.l	messages&~WM,x
	sta	friends_sound
	inx
	stx	friends_msg

	lda	#50
	sta	msg_count1
	stz	msg_count2
.finished
	plp
	rtl
.finished2
	pla
	plp
	rtl
	
	
	
; a = message to send
send_message2_l
	php
	ai16
	and	#255
	dec	a
	cmp	#-1
	beq	.finished
	asl	a
	tax
	lda.l	messages2,x
	tax
	a8
	lda.l	messages2&~WM,x
	pha
	a16
	and	#127
	tay
	a8

;	lda.w	friends_hp-1,y
;	beq	.finished2

	lda	friends_meter
	inc	a
	bne	.nometer
	lda.w	friends_hp-1,y
	ora	#128
	sta	friends_meter
	bra	.meteron
	
.nometer	stz	friends_meter
.meteron
	pla
	sta	whichfriend

	inx
	lda.l	messages2&~WM,x
	sta	friends_sound
	inx
	stx	friends_msg

	lda	#50
	sta	msg_count1
	stz	msg_count2
.finished
	plp
	rtl
.finished2
	pla
	plp
	rtl

send_messagex_l
	php
	ai16
	and	#255
	dec	a
	cmp	#-1
	beq	.finished
	asl	a
	tax
	lda.l	messages,x
	tax
	a8
	lda.l	messages&~WM,x
	pha
	a16
	and	#127
	tay
	a8

;	lda.w	friends_hp-1,y
;	beq	.finished2

	lda	friends_meter
	inc	a
	bne	.nometer
	lda.w	friends_hp-1,y
	ora	#128
	sta	friends_meter
	bra	.meteron
	
.nometer	stz	friends_meter
.meteron
	pla
	sta	whichfriend2

	inx
	lda.l	messages&~WM,x
	sta	friends_sound
	inx
	stx	friends_msg2

	lda	#50
	sta	msg_count12
	stz	msg_count22
.finished
	plp
	rtl
.finished2
	pla
	plp
	rtl
	
	
	
; a = message to send
send_messagex2_l
	php
	ai16
	and	#255
	dec	a
	cmp	#-1
	beq	.finished
	asl	a
	tax
	lda.l	messages2,x
	tax
	a8
	lda.l	messages2&~WM,x
	pha
	a16
	and	#127
	tay
	a8

;	lda.w	friends_hp-1,y
;	beq	.finished2

	lda	friends_meter
	inc	a
	bne	.nometer
	lda.w	friends_hp-1,y
	ora	#128
	sta	friends_meter
	bra	.meteron
	
.nometer	stz	friends_meter
.meteron
	pla
	sta	whichfriend2

	inx
	lda.l	messages2&~WM,x
	sta	friends_sound
	inx
	stx	friends_msg2

	lda	#50
	sta	msg_count12
	stz	msg_count22
.finished
	plp
	rtl
.finished2
	pla
	plp
	rtl

openingframes	=	5

friends_messages_l
	php
	a8
;	s_jmp_varAND	B,gameflags,#gf_playerdying!gf_playerdead,.finished

	lda	msg_count1
	lbeq	.closedown

	lda	msg_count2
	cmp	#openingframes
	lbcc	.openup

	jsl	random_l
	and	#31
	bne	.norm
	lda	#4
	bra	.doit
.norm
	and	#1
	sta	x1

	lda	msg_count1
	cmp	#30
	bcs	.normanim
	stz	x1
.normanim
	
	lda	whichfriend
	and	#127
	asl	a
	clc
	adc	#openingframes
	adc	x1
.doit
	jsr	displayface
	dec	msg_count1
	bne	.nosound
	trigse	$64
.nosound

; shadow
	lda	playertwoactivated
	beq	.normtxt
	
	ldx	friends_msg
	ai16
	lda	#83
	sta.l	m_x1
	lda	#160
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter
	a8
	lda	#msprintstr>>16
	ldx	#msprintstr&WM
	jsl	runmario_l

; real text
	ldx	friends_msg
	ai16
	lda	#82
	sta.l	m_x1
	lda	#159
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter
	a8
	lda	#mfprintstr>>16
	ldx	#mfprintstr&WM
	jsl	runmario_l
	bra	.donetxt
.normtxt
	ldx	friends_msg
	ai16
	lda	#83
	sta.l	m_x1
	lda	#148
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter
	a8
	lda	#msprintstr>>16
	ldx	#msprintstr&WM
	jsl	runmario_l

; real text
	ldx	friends_msg
	ai16
	lda	#82
	sta.l	m_x1
	lda	#147
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter
	a8
	lda	#mfprintstr>>16
	ldx	#mfprintstr&WM
	jsl	runmario_l
.donetxt


; display the hp meter?
	lda	friends_meter
	beq	.nothingdoing
	and	#127
	sta	x1
	lda	whichfriend
	a16
	and	#127
	tay
	a8
	lda.w	friends_hp-1,y
	cmp	x1
	beq	.same

	lda	x1
	dec	a
	ora	#128
	sta	friends_meter

.same	a16
	and	#127
	sta.l	m_z1
	lda	#82
	sta.l	m_x1

	lda	playertwoactivated
	beq	.normy
	lda	#172
	sta.l	m_y1
	bra	.doney
.normy
	lda	#156
	sta.l	m_y1
.doney
	call_mario	mshowteammate2
.nothingdoing
	a8

	bra	.finished
.closedown
	lda	msg_count2
	dec	a
	bmi	.finished
	sta	msg_count2
	jsr	displayface
	bra	.finished
.openup
	jsr	displayface
	inc	msg_count2
	lda	msg_count2
	cmp	#openingframes
	bcc	.finished
	lda	whichfriend
	and	#127
	asl	a
	asl	a
	clc
	adc	friends_sound
	a16
	and	#255
	tax
	a8
	lda.l	facesounds,x
	trigse	a

.finished
	plp
	rtl

chkmeter
	php
	a8
	lda	whichfriend
	bit	#128
	bne	.3lines
	and	#127
	cmp	#friend_andross
	beq	.3lines
	lda	friends_meter
	beq	notshowing
.3lines
	a16
	lda.l	m_y1
	sec
	sbc	#16
	sta.l	m_y1
notshowing
	plp
	rts
	
	
friends_messages2_l
	php
	a8
;	s_jmp_varAND	B,gameflags,#gf_playerdying!gf_playerdead,.finished

	lda	msg_count12
	lbeq	.closedown

	lda	msg_count22
	cmp	#openingframes
	lbcc	.openup

	jsl	random_l
	and	#31
	bne	.norm
	lda	#4
	bra	.doit
.norm
	and	#1
	sta	x1

	lda	msg_count12
	cmp	#30
	bcs	.normanim
	stz	x1
.normanim
	
	lda	whichfriend2
	and	#127
	asl	a
	clc
	adc	#openingframes
	adc	x1
.doit
	jsr	displayface2
	dec	msg_count12
	bne	.nosound
	trigse	$64
.nosound

; shadow
	lda	playertwoactivated
	beq	.normtxt
	
	ldx	friends_msg2
	ai16
	lda	#83
	sta.l	m_x1
	lda	#160
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter2
	a8
	lda	#msprintstr>>16
	ldx	#msprintstr&WM
	jsl	runmario_l

; real text
	ldx	friends_msg2
	ai16
	lda	#82
	sta.l	m_x1
	lda	#159
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter2
	a8
	lda	#mfprintstr>>16
	ldx	#mfprintstr&WM
	jsl	runmario_l
	bra	.donetxt
.normtxt
	ldx	friends_msg2
	ai16
	lda	#83
	sta.l	m_x1
	lda	#148
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter2
	a8
	lda	#msprintstr>>16
	ldx	#msprintstr&WM
	jsl	runmario_l

; real text
	ldx	friends_msg2
	ai16
	lda	#82
	sta.l	m_x1
	lda	#147
	sta.l	m_y1
	txa
	sta.l	m_txtdata
	jsr	chkmeter2
	a8
	lda	#mfprintstr>>16
	ldx	#mfprintstr&WM
	jsl	runmario_l
.donetxt


; display the hp meter?
	lda	friends_meter
	beq	.nothingdoing
	and	#127
	sta	x1
	lda	whichfriend2
	a16
	and	#127
	tay
	a8
	lda.w	friends_hp-1,y
	cmp	x1
	beq	.same

	lda	x1
	dec	a
	ora	#128
	sta	friends_meter

.same	a16
	and	#127
	sta.l	m_z1
	lda	#82
	sta.l	m_x1

	lda	playertwoactivated
	beq	.normy
	lda	#172
	sta.l	m_y1
	bra	.doney
.normy
	lda	#156
	sta.l	m_y1
.doney
	call_mario	mshowteammate2
.nothingdoing
	a8

	bra	.finished
.closedown
	lda	msg_count22
	dec	a
	bmi	.finished
	sta	msg_count22
	jsr	displayface2
	bra	.finished
.openup
	jsr	displayface2
	inc	msg_count22
	lda	msg_count22
	cmp	#openingframes
	bcc	.finished
	lda	whichfriend2
	and	#127
	asl	a
	asl	a
	clc
	adc	friends_sound
	a16
	and	#255
	tax
	a8
	lda.l	facesounds2,x
	trigse	a

.finished
	plp
	rtl

chkmeter2
	php
	a8
	lda	whichfriend2
	bit	#128
	bne	.3lines
	and	#127
	cmp	#friend_andross
	beq	.3lines
	lda	friends_meter
	beq	notshowing2
.3lines
	a16
	lda.l	m_y1
	sec
	sbc	#16
	sta.l	m_y1
notshowing2
	plp
	rts
	
facesounds2
	db	$8c	; blackyoshi 
	db	$8c	; blackyoshi help
	db	$8c	; blackyoshi down
	db	$8c	; blackyoshi other
	db	45	; rob
	db	45	; rob help
	db	45	; rob down
	db	45	; rob other
	db	$8c	; craig
	db	$8c	; craig help
	db	$8c	; craig down
	db	$8c	; craig other
	db	$8c	; panther
	db	$8c	; panther help
	db	$8c	; panther down
	db	$8c	; panther other
	db	$8c	; link
	db	$8c	; link help
	db	$8c	; link down
	db	$8c	; link other
	db	$8c	; kirbo
	db	$8c	; kirbo help
	db	$8c	; kirbo down
	db	$8c	; kirby other
	db	$8c	; walrus
	db	$8c	; walrus help
	db	$8c	; walrus down
	db	$8c	; walrus other
	db	$8c	; samus
	db	$8c	; samus help
	db	$8c	; samus down
	db	$8c	; samus other
	db	$8c	; toad
	db	$8c	; toad help
	db	$8c	; toad down
	db	$8c	; toad other
	db	$8c	; rex
	db	$8c	; rex help
	db	$8c	; rex down
	db	$8c	; rex other
	
	
facesounds
	db	$60	; fox
	db	$60	; fox
	db	$60	; fox
	db	$60	; fox
	db	$7c	; rabbit help
	db	$7d	; rabbit down
	db	$62	; rabbit other
	db	$62	; rabbit
	db	$7a	; falcon help
	db	$7b	; falcon down
	db	$61	; falcon other
	db	$61	; falcon
	db	$7e	; frog help
	db	$7f	; frog down
	db	$63	; frog other
	db	$63	; frog
	db	$5f	; pepper help
	db	$5f	; pepper down
	db	$5f	; pepper other
	db	$5f	; pepper
	db	$8c	; andross help
	db	$8c	; andross down
	db	$8c	; andross other
	db	$8c	; andross
	db	$8c	; wolf help
	db	$8c	; wolf down
	db	$8c	; wolf other
	db	$8c	; wolf
	db	$8c	; pigma help
	db	$8c	; pigma down
	db	$8c	; pigma other
	db	$8c	; pigma
	db	$8c	; andrew help
	db	$8c	; andrew down
	db	$8c	; andrew other
	db	$8c	; andrew
	db	$8c	; leon help
	db	$8c	; leon down
	db	$8c	; leon other
	db	$8c	; leon
	db	161	; wolfdown help
	db	161	; wolfdown down
	db	161	; wolfdown other
	db	161	; wolfdown
	db	161	; pigmadown help
	db	161	; pigmadown down
	db	161	; pigmadown other
	db	161	; pigmadown
	db	161	; andrewdown help
	db	161	; andrewdown down
	db	161	; andrewdown other
	db	161	; andrewdown
	db	161	; leondown help
	db	161	; leondown down
	db	161	; leondown other
	db	161	; leondown
	db	$8c	; luigi help
	db	$8c	; luigi down
	db	$8c	; luigi other
	db	$8c	; luigi
	db	$8c	; mario help
	db	$8c	; mario down
	db	$8c	; mario other
	db	$8c	; mario
	db	$8c	; mrl help
	db	$8c	; mrl down
	db	$8c	; mrl other
	db	$8c	; mrl
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm
	db	$8c	; mrl
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm
	db	$8c	; mrm help
	db	$8c	; mrm down
	db	$8c	; mrm other
	db	$8c	; mrm



displayface
; a is frame to show
	php
	a16
	and	#255
	xba
	sta	x1
	lsr	x1	; *128
	asl	a	; *512
	adc	x1
	adc	#facedata&WM
	sta.l	m_faceptr
	lda	#6
	sta.l	m_bigx
	lda	playertwoactivated
	beq	normface
	lda	#18*8
	sta.l	m_bigy
	bra	doneface
normface
	lda	#16*8
	sta.l	m_bigy
doneface
	call_mario	mcopyface
	plp
	rts
	
displayface2
; a is frame to show
	php
	a16
	and	#255
	xba
	sta	x1
	lsr	x1	; *128
	asl	a	; *512
	adc	x1
	adc	#facedata2&WM
	sta.l	m_faceptr
	lda	#6
	sta.l	m_bigx
	lda	playertwoactivated
	beq	normface2
	lda	#18*8
	sta.l	m_bigy
	bra	doneface2
normface2
	lda	#16*8
	sta.l	m_bigy
doneface2
	call_mario	mcopyface2
	plp
	rts


;-------------------------------------------------

foxy_option	equ	ocode1
foxy_frame	equ	ocode2
foxy_xa	equ	cla1
foxy_ya	equ	cla2
foxy_za	equ	clb1
foxy_foot	equ	clb2
foxy_ptr	equ	clac
foxy_shape	equ	clam
foxy_flag	equ	clbm

setcharmapfox_l
	php
	a8
	lda	#128
	sta	vmainc
	ai16
	lda	#vsc_base1+32*gameStRow		;128
	sta	vmaddl
	a8
	lda	stopcounting
	cmp	#10
	beq	.normal
	cmp	#12
	beq	.normal
	cmp	#1
	beq	.normal
	lda	pgbg
	cmp	#13
	beq	.brown
	cmp	#14
	beq	.brown
;	cmp	#26
;	beq	.test
	cmp	#4
	beq	.yellow
	cmp	#10
	beq	.yellow
	cmp	#32
	beq	.yellow
	cmp	#36
	beq	.test
	bra	.normal


.brown
	a16
	lda	#1024*9
	bra	.done
.yellow
	a16
	lda	#1024*8
	bra	.done
.test
	a16
	lda	#1024*4
	bra	.done
	
	
.normal
	a16
	lda	#1024*7
.done
	ldy	#0
lolv
	pha
	lda	#gamenum_col*gamenum_row+(6<<10)
	rept	(32-gamenum_col)/2		;clear out borders
	sta	vmdatal
	endr
	pla

	ldx	#0
lolh	sta	vmdatal
	clc
	adc	#gamenum_row
	inx
	cpx	#gamenum_col
	bne	lolh

	pha
	lda	#gamenum_col*gamenum_row+(6<<10)
	rept	(32-gamenum_col)/2
	sta	vmdatal
	endr
	pla

	sec
	sbc	#gamenum_col*gamenum_row-1
	iny
	cpy	#gamenum_row
	bne	lolv
	plp
	rtl

;-------------------------------------------------

foxcursor equ	$3c

	spralc	; reset the sprmalc pointer
	spralc	spr_foxeye,14
	spralc	spr_foxarm,16
	spralc	spr_foxfoot,6
	spralc	spr_foxcursor,1

;-------------------------------------------------
fox_sprites_l
	php
	a8i16
	lda	stopcounting
	bne	skip1
	lda	#179
	sta	spr_foxcursor+1
	lda	foxy_option
	bne	other
	lda	#45
	bra	con
other	lda	#93
con	sta	spr_foxcursor
	lda	#foxcursor+spradd
	sta	spr_foxcursor+2
	lda	#%110000
	sta	spr_foxcursor+3
skip1
nopla
	lda	foxy_frame
	a16
	and	#254
	cmp	#8
	bcc	ok1
	lda	#6
ok1
	tax
	lda.l	foxarmanim,x
	tax
	a8
	pha
	lda	stopcounting
	bne	skip2
	pla
	ldy	#spr_foxarm
	jsr	copyfoxsprites
	bra	nopla2
skip2
	pla
nopla2
	lda	foxy_frame
	sec
	sbc	#8
	bmi	nodo
	a16
	and	#254
	cmp	#8
	bmi	ok2
	lda	#6
ok2
	tax
	lda.l	foxeyeanim,x
	tax
	a8
	lda	stopcounting
	bne	nodo
	ldy	#spr_foxeye
	jsr	copyfoxsprites

nodo
	lda	foxy_foot
	a16
	and	#7
	asl	a
	tax
	lda.l	foxfootanim,x
	tax
	a8
	lda	stopcounting
	bne	skip3
	ldy	#spr_foxfoot
	jsr	copyfoxsprites
skip3
	lda	foxy_foot
	and	#7
	beq	daijobu
	inc	foxy_foot
	bra	nornd
daijobu
	lda	foxy_foot
	bit	#128
	beq	.norm
	jsl	random_l
	and	#31
	bne	nornd
	lda	#129
	sta	foxy_foot
	bra	nornd
.norm
	jsl	random_l
	and	#127
	bne	nornd
	lda	foxy_foot
	clc
	adc	#8
	sta	foxy_foot
nornd


	plp
	rtl

;-------------------------------------------------
; copyfoxsprites:
;
; entry: x is a pointer to sprite list
;        y is a pointer to the sprite buffer
;-------------------------------------------------

foxsprites
fox_x	=	foxsprites
fox_y	=	foxsprites+1
fox_chr	=	foxsprites+2
fox_size	=	3

	longi
copyfoxsprites
	php
	a8
andagain
	lda.l	fox_x,x
	cmp	#-1
	beq	fin
	sta.w	0,y
	lda.l	fox_y,x
	sta.w	1,y
	lda.l	fox_chr,x
	sta.w	2,y
	lda	#%110000
	sta.w	3,y
	iny
	iny
	iny
	iny
	inx
	inx
	inx
	bra	andagain
fin
	plp
	rts




foxanim	macro
foxx	=	\1
foxy	=	\2
	endm

foxspr	macro
	db	(foxx+(\1)*8)&BM,(foxy+(\2)*8)&BM
	db	\3+spradd
	endm

foxend	macro
	db	-1,-1
	endm


foxeyeanim
	dw	foxeyeanim1-foxsprites
	dw	foxeyeanim1-foxsprites
	dw	foxeyeanim2-foxsprites
	dw	foxeyeanim3-foxsprites
	dw	foxeyeanim2-foxsprites

foxarmanim
	dw	foxarmanim1-foxsprites
	dw	foxarmanim2-foxsprites
	dw	foxarmanim3-foxsprites
	dw	foxarmanim3-foxsprites
	dw	foxarmanim2-foxsprites


foxfootanim
	dw	foxfootanim1-foxsprites
	dw	foxfootanim2-foxsprites
	dw	foxfootanim3-foxsprites
	dw	foxfootanim2-foxsprites
	dw	foxfootanim1-foxsprites
	dw	foxfootanim2-foxsprites
	dw	foxfootanim3-foxsprites
	dw	foxfootanim2-foxsprites

foxeyeanim1
	foxanim	184,55
	foxspr	1,0,$00
	foxspr	2,0,$01
	foxspr	3,0,$02
	foxspr	4,0,$03
	foxspr	0,1,$04
	foxspr	1,1,$05
	foxspr	2,1,$06
	foxspr	3,1,$07
	foxspr	4,1,$08
	foxspr	0,2,$09
	foxspr	1,2,$0a
	foxspr	2,2,$0b
	foxspr	3,2,$0c
	foxspr	4,2,$0d
	foxend


foxeyeanim2
	foxanim	184,55
	foxspr	1,0,$00
	foxspr	2,0,$0e
	foxspr	3,0,$0f
	foxspr	4,0,$10
	foxspr	0,1,$04
	foxspr	1,1,$05
	foxspr	2,1,$11
	foxspr	3,1,$12
	foxspr	4,1,$08
	foxspr	0,2,$09
	foxspr	1,2,$0a
	foxspr	2,2,$13
	foxspr	3,2,$0c
	foxspr	4,2,$0d
	foxend

foxeyeanim3
	foxanim	184,55
	foxspr	1,0,$00
	foxspr	2,0,$01
	foxspr	3,0,$14
	foxspr	4,0,$15
	foxspr	0,1,$04
	foxspr	1,1,$05
	foxspr	2,1,$06
	foxspr	3,1,$07
	foxspr	4,1,$16
	foxspr	0,2,$09
	foxspr	1,2,$0a
	foxspr	2,2,$17
	foxspr	3,2,$0c
	foxspr	4,2,$0d
	foxend

foxarmanim1
	foxanim	176,80
	foxspr	2,0,$1a
	foxspr	1,1,$33
	foxspr	2,1,$1e
	foxspr	0,2,$34
	foxspr	1,2,$35
	foxspr	2,2,$36
	foxspr	0,3,$37
	foxspr	1,3,$38
	foxspr	2,3,$39
	foxspr	1,4,$3a
	foxspr	2,4,$3b
	foxspr	2,5,$31
	foxspr	10,17,$54
	foxspr	10,17,$54
	foxspr	10,17,$54
	foxspr	10,17,$54
	foxend

foxarmanim2
	foxanim	176,80
	foxspr	2,0,$1a
	foxspr	0,1,$28
	foxspr	1,1,$29
	foxspr	2,1,$1e
	foxspr	0,2,$2a
	foxspr	1,2,$2b
	foxspr	2,2,$2c
	foxspr	0,3,$2d
	foxspr	1,3,$2e
	foxspr	2,3,$2f
	foxspr	2,4,$30
	foxspr	2,5,$31
	foxspr	10,17,$60
	foxspr	10,17,$60
	foxspr	10,17,$60
	foxspr	10,17,$60
	foxend

foxarmanim3
	foxanim	168,80
	foxspr	0,0,$18
	foxspr	1,0,$19
	foxspr	3,0,$1a
	foxspr	0,1,$1b
	foxspr	1,1,$1c
	foxspr	2,1,$1d
	foxspr	3,1,$1e
	foxspr	0,2,$1f
	foxspr	1,2,$20
	foxspr	2,2,$21
	foxspr	3,2,$22
	foxspr	1,3,$23
	foxspr	2,3,$24
	foxspr	3,3,$25
	foxspr	3,4,$26
	foxspr	3,5,$27
	foxend


foxfootanim1
	foxanim	215,167
	foxspr	0,0,$3d
	foxspr	1,0,$3e
	foxspr	2,0,$3f
	foxspr	0,1,$40
	foxspr	1,1,$41
	foxspr	2,1,$42
	foxend

;	foxspr	2,0,$3d
;	foxspr	0,1,$3e
;	foxspr	1,1,$3f
;	foxspr	2,1,$40
;	foxspr	0,10,$60
;	foxspr	0,10,$60
;	foxend

foxfootanim2
	foxanim	215,167
	foxspr	0,0,$43
	foxspr	1,0,$44
	foxspr	2,0,$45
	foxspr	0,1,$46
	foxspr	1,1,$47
	foxspr	2,1,$48
	foxend

;	foxanim	184,151
;	foxspr	0,0,$41
;	foxspr	1,0,$42
;	foxspr	2,0,$3d
;	foxspr	0,1,$43
;	foxspr	1,1,$44
;	foxspr	2,1,$40
;	foxend

foxfootanim3
	foxanim	215,167
	foxspr	0,0,$49
	foxspr	1,0,$4a
	foxspr	2,0,$4b
	foxspr	0,1,$4c
	foxspr	1,1,$4d
	foxspr	2,1,$4e
	foxend

;	foxanim	184,151
;	foxspr	0,0,$45
;	foxspr	1,0,$46
;	foxspr	2,0,$3d
;	foxspr	0,1,$47
;	foxspr	1,1,$48
;	foxspr	2,1,$40
;	foxend


;specialmenuboot_l
;	init_bg	mode1
;	bg2chr	and
;	bg2scr	and
;	palette	2e
;	set_bg
;	jsl	specialmenu_l
;	rtl

clearsprites_l
	php
	a8i16
	ldx	#128*4+128/4		; clear the buffer
lp2	stz	spriteblk,x
	dex
	bpl	lp2

	jsl	dma_sprites_L
	plp
	rtl

;-------------------------------------------------
dma_sprites_l
	php
	a8i16
	dmaoaram	0,0,spriteblk,512+128/4	; transfer oam
	plp
	rtl

foxytrans_l
	php
	a8i16
aha2
	lda	stopcounting
	cmp	#9
	bne	.normal
	jsr	drawsome3d
	
.normal
	lda	trans_flag
	bne	aha2

	lda	#tm_fox
	sta	trans_flag

waitx	lda	transbmp1
	beq	waitx
	jsl	clronehalf_l
waitxx
	lda	transbmp1
	cmp	#2
	bne	waitxx

	stz	transbmp1

	jsl	clrotherhalf_l

	jsl	fox_sprites_l
	lda	stopcounting
	cmp	#9
	beq	.dontdrawagain
	jsr	drawsome3d
.dontdrawagain
	a8
	IFEQ	1	;removed			;fastrom only
	lda	nobgmode
	lbne	.nocolortrip
	lda	pgbg
	cmp	#2
	bne	.norb
	jsl	palfadetonewspace1_l
	jsl	palfadetonewspace2_l
	jsl	palfadetonewspace3_l
	jsl	palfadetonewspace4_l
	jsl	palfadetonewspace5_l
.norb
	lda	pgbg
	cmp	#7
	beq	.yama
	jsl	palgoto2_l
	jsl	palfadetofxgreen_l
	jsl	palfadetofxdes_l
	jsl	palfadetofxpink_l
	jsl	palfadetofxblue_l
	bra	.noyama
.yama
	jsl	palfadetoyamao_l
	jsl	palfadetoyamab_l
.noyama
	lda	colortrip
	beq	.nocolortrip
	jsl	palfaderandom_l
.nocolortrip
	ENDC
	plp
	rtl

foxytrans2_l
	php
	a8i16
aha22
	lda	stopcounting
	cmp	#9
	bne	.normal
	jsr	drawsome3d
	
.normal
	lda	trans_flag
	bne	aha22

	lda	#tm_fox
	sta	trans_flag

waitx2	lda	transbmp1
	beq	waitx2
	jsl	clronehalf_l
waitxx2
	lda	transbmp1
	cmp	#2
	bne	waitxx2

	stz	transbmp1

	jsl	clrotherhalf_l

	jsl	fox_sprites_l
	lda	stopcounting
	cmp	#9
	beq	.dontdrawagain
	jsr	drawsome3d
.dontdrawagain
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.yama
	jsl	palfadetofxgreen_l
	jsl	palfadetofxdes_l
	jsl	palfadetofxpink_l
	jsl	palfadetofxblue_l
	bra	.noyama
.yama
	jsl	palfadetoyamao_l
	jsl	palfadetoyamab_l
.noyama
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff

.nopalstuff
	ENDC
	plp
	rtl	
;-------------------------------------------------

drawsome3d
	php
	a16
	lda	#0
	sta.l	m_bigx
	sta.l	m_bigy
	sta.l	m_depthoffset


	inc	gameframe
	lda	foxy_shape
	sta.l	m_shapeptr

	movi 0,clx1
	movi gamenum_col*8-1,clx2
	movi 0,cly1
	movi gamenum_row*8-1,cly2
	movi gamenum_col*4,vanishx
	movi gamenum_row*4,vanishy

	a8i16
	lda.l	m_rotz
	pha
	lda.l	m_roty
	pha
	lda.l	m_rotx
	pha

	lda	#mshowobj3>>16
	ldx	#mshowobj3&WM
	jsl	runmario_l

	a8
	pla
	clc
	adc	foxy_xa
	sta.l	m_rotx

	pla
	clc
	adc	foxy_ya
	sta.l	m_roty

	pla
	clc
	adc	foxy_za
	sta.l	m_rotz

	lda	#0
	sta.l	m_rotx+1
	sta.l	m_roty+1
	sta.l	m_rotz+1

	a16
	plp
	rts



setdefaultpos
	a8
	lda	stopcounting
	and	#15
	cmp	#12
	beq	adjusted
	cmp	#10
	beq	adjusted
	cmp	#14
	beq	adjusted
	cmp	#9
	beq	adjustedpregame
	cmp	#5
	beq	adjusted
	cmp	#1
	beq	shipselectscreenx
	lda	#9*8+4
	bra	doneadjusting
shipselectscreenx
	lda	#13*8+4
	bra	doneadjusting
adjustedpregame
	lda	#21*8+4
	bra	doneadjusting
adjusted
	lda	#13*8+4
doneadjusting
	sta.l	m_vanishx
	
	lda	stopcounting
	and	#15
	cmp	#1
	beq	shipselectscreeny
	cmp	#9
	beq	adjustedy
	lda	#7*8+32+4
	bra	donewithy
shipselectscreeny
	lda	#9*8+32+4
	bra	donewithy
adjustedy
	lda	#17*8+32+4	
donewithy
	sta.l	m_vanishy
	rtl


doanimation
	lda	gameframe
	sta.l	m_framenum
	sta.l	m_colframe
	rtl


scrollthebg
	a8
	lda	tempval4
	bne	.decscroll

	inc	tempval3
	lda	tempval3
	cmp	#254
	lbeq	.reversescroll
	sta	$210F
	stz	$210F
	jmp	.donewithscroll
.decscroll
	dec	tempval3
	lda	tempval3
	lbeq	.reversescrollback
	sta	$210F
	stz	$210F
	jmp	.donewithscroll
.reversescroll
	lda	#1
	sta	tempval4
	dec	tempval3
	lda	tempval3
	sta	$210F
	stz	$210F

	bra	.donewithscroll
.reversescrollback
	stz	tempval4
	inc	tempval3
	lda	tempval3
	sta	$210F
	stz	$210F

.donewithscroll
;	jsl	do_hpositions_l
	rtl

randomizebg				;randomize the pregame bg
	a8
.again
	jsl	random_l
	and #63
	cmp	#36+1		;last entry for bgs
	bpl	.again
	sta	pgbg


	rtl
	
bgtime
	lda	stopcounting					;more bg stuff, skip if not in model test or pre-game menu
	lbeq	regbg
dothebg	
	lda	pgbg
	lbeq	macbeth2
	cmp	#1
	lbeq	fortuna2
	cmp	#2
	lbeq	sectork2x
	cmp	#3
	lbeq	alphacorn2
	cmp	#4
	lbeq	fxdescorn2
	cmp	#5
	lbeq	desert2
	cmp	#6
	lbeq	asteroidfield
	cmp	#7
	lbeq	yamabg
	cmp	#8
	lbeq	vortexdes
	cmp	#9
	lbeq	citycity
	cmp	#10
	lbeq	alphaalpha
	cmp	#11
	lbeq	vhwypurple
	cmp	#12
	lbeq	venomalpha
	cmp	#13
	lbeq	vortexice1
	cmp	#14
	lbeq	vortexcloud
	cmp	#15
	lbeq	cornblu
	cmp	#16
	lbeq	cornblu
	cmp	#17
	lbeq	starsbg
	cmp	#18
	lbeq	specialbg
	cmp	#19
	lbeq	bgfor34
	cmp	#20
	lbeq	bgfor14
	cmp	#21
	lbeq	lsbbg
	cmp	#22
	lbeq	f1bg
	cmp	#23
	lbeq	lastbg
	cmp	#24
	lbeq	lastbg
	cmp	#25
	lbeq	a2222
	cmp	#26
	lbeq	a2323
	cmp	#27
	lbeq	a3232
	cmp	#28
	lbeq	a3434
	cmp	#29
	lbeq	a2424
	cmp	#30
	lbeq	dobholebg
	cmp	#31
	lbeq	dointrobg
	cmp	#32
	lbeq	dofortn
	cmp	#33
	lbeq	tbossmenu
	cmp	#34
	lbeq	venomhwymenu
	cmp	#35
	lbeq	finalspacemenu
	cmp	#36
	lbeq	sunmenu
	cmp	#99
	lbeq	blackout




sunmenu
	decvramnotrans		0,vchr_logback,bgsunccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgsunmenupcr,8*k				;blank stuff
	jmp	donebg
tbossmenu
	decvramnotrans		0,vchr_logback,bgtbosmenuccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgtbosmenupcr,8*k				;blank stuff
	jmp	donebg
venomhwymenu
	decvramnotrans		0,vchr_logback,bgvhwymenuccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvhwymenupcr,8*k				;blank stuff
	jmp	donebg
finalspacemenu
	decvramnotrans		0,vchr_logback,bgfinalspaceccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgfinalspacepcr,8*k				;blank stuff
	jmp	donebg
dofortn
	decvramnotrans		0,vchr_logback,bg33ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg33pcr,8*k				;blank stuff
	jmp	donebg
dobholebg
	decvramnotrans		0,vchr_logback,bgholeaccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgholeapcr,8*k				;blank stuff
	jmp	donebg
dointrobg
	decvramnotrans		0,vchr_logback,bgdemoccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgdemopcr,8*k				;blank stuff
	jmp	donebg
a3434
	decvramnotrans		0,vchr_logback,bg34ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg34pcr,8*k				;blank stuff
	jmp	donebg
a3232
	decvramnotrans		0,vchr_logback,bg32ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg32pcr,8*k				;blank stuff
	jmp	donebg
a2424
	decvramnotrans		0,vchr_logback,bg24ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg24pcr,8*k				;blank stuff
	jmp	donebg
;letstsp
;	decvramnotrans		0,vchr_logback,bgtspccr,6*k			;blank stuff
;	decbg2vramnotrans	0,vsc_base2,bgtfspcr,8*k				;blank stuff
;	jmp	donebg
;dothebm
;	decvramnotrans		0,vchr_logback,bgbmccr,$40*32			;blank stuff
;	decbg2vramnotrans	0,vsc_base2,bg23bpcr,8*k				;blank stuff
;	jmp	donebg
a2222
	decvramnotrans		0,vchr_logback,bg22ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg22pcr,8*k				;blank stuff
	jmp	donebg
a2323
	decvramnotrans		0,vchr_logback,bg23ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg23menupcr,8*k				;blank stuff
	jmp	donebg
lsbbg
	decvramnotrans		0,vchr_logback,bglsbccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bglsbpcr,8*k				;blank stuff
	jmp	donebg
f1bg
	decvramnotrans		0,vchr_logback,bgf1ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgf1pcr,8*k				;blank stuff
	jmp	donebg
lastbg
	decvramnotrans		0,vchr_logback,bgbholeccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bglastpcr,8*k				;blank stuff
	jmp	donebg
bgfor34
	decvramnotrans		0,vchr_logback,bg34ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg34pcr,8*k				;blank stuff
	jmp	donebg
bgfor14
	decvramnotrans		0,vchr_logback,bg14ccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bg14pcr,8*k				;blank stuff
	jmp	donebg
specialbg
	decvramnotrans		0,vchr_logback,bgmccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgmpcr,8*k				;blank stuff
	jmp	donebg
starsbg
	decvramnotrans		0,vchr_logback,bgstarsccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgstarspcr,8*k				;blank stuff
	jmp	donebg
cornblu
	decvramnotrans		0,vchr_logback,bgstpccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgstppcr,8*k				;blank stuff
	jmp	donebg
vortexice1
	decvramnotrans		0,vchr_logback,bgvoriceccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvoricepcr,8*k				;blank stuff
	jmp	donebg
vortexcloud
	decvramnotrans		0,vchr_logback,bgvorcloccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvorclopcr,8*k				;blank stuff
	jmp	donebg
venomalpha
	decvramnotrans		0,vchr_logback,bgvenomaccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvenomapcr,8*k				;blank stuff
	jmp	donebg
alphaalpha
	decvramnotrans		0,vchr_logback,bgalphaccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgalphapcr,8*k				;blank stuff
	jmp	donebg
vhwypurple
	decvramnotrans		0,vchr_logback,bgvhwypccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvhwyppcr,8*k				;blank stuff
	jmp	donebg
citycity
	decvramnotrans		0,vchr_logback,bgcityccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgcitypcr,8*k				;blank stuff
	jmp	donebg
vortexdes
	decvramnotrans		0,vchr_logback,bgvordesccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgvordespcr,8*k				;blank stuff
	jmp	donebg
yamabg
	decvramnotrans		0,vchr_logback,bgyamaccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgyamapcr,8*k				;blank stuff
	jmp	donebg
fxdescorn2
	decvramnotrans		0,vchr_logback,bgfxdesccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgfxdmenupcr,8*k				;blank stuff
	jmp	donebg
desert2
	decvramnotrans		0,vchr_logback,bgdesertccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgdesmenupcr,8*k				;blank stuff
	jmp	donebg
fortuna2
	decvramnotrans		0,vchr_logback,bgfortnccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgfortmenupcr,8*k				;blank stuff
	jmp	donebg
sectork2x
	decvramnotrans		0,vchr_logback,bgrbccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgseckmenupcr,8*k				;blank stuff
	jmp	donebg
alphacorn2
	decvramnotrans		0,vchr_logback,bgcornccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgcornmenupcr,8*k				;blank stuff
	jmp	donebg
macbeth2
	decvramnotrans		0,vchr_logback,bgmacbethccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgmenumacpcr,8*k				;blank stuff
	jmp	donebg
asteroidfield
	decvramnotrans		0,vchr_logback,bgasteroidccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgasteroidpcr,8*k				;blank stuff
	jmp	donebg
blackout
	decvramnotrans		0,vchr_logback,bgasteroidccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgblankpcr,8*k				;blank stuff
	jsl	makebg2black_l
	jmp	donebg
regbg
	decvramnotrans		0,vchr_logback,bgfoxccr,6*k				;continue screen stuff
	decbg2vramnotrans	0,vsc_base2,bgfoxpcr,8*k			;
donebg

	rtl
	
	
dopalstuff_l
	lda	stopcounting					;Important stuff here, load this into accumulator
	beq	.regreg
	bra	nobg1							;if its 8 or more, no fox background
.regreg
	dmacgram	0,0,(bgfoxpac),512		;Yes Fox
	jmp	goon1
nobg1
;	dmacgram	0,0,test1,512				;No Fox
;	dmacgram	0,0,test1,512				;No Fox
	lda	pgbg
	lbeq	macbeth1
	cmp	#1
	lbeq	fortuna1
	cmp	#2
	lbeq	sectork1x
	cmp	#3
	lbeq	alphacorn1
	cmp	#4
	lbeq	fxdescorn1
	cmp	#5
	lbeq	desert1
	cmp	#6
	lbeq	sectork1x
	cmp	#7
	lbeq	yamapal
	cmp	#8
	lbeq	vortexpal
	cmp	#9
	lbeq	citypal
	cmp	#10
	lbeq	fxbluecorn1
	cmp	#11
	lbeq	alphacorn1
	cmp	#12
	lbeq	fxdescorn1
	cmp	#13
	lbeq	vortexpal
	cmp	#14
	lbeq	vortexpal
	cmp	#15
	lbeq	a2dpal
	cmp	#16
	lbeq	a2gpal
	cmp	#17
	lbeq	starspalthx
	cmp	#18
	lbeq	spacepalthx
	cmp	#19
	lbeq	spacepalthx
	cmp	#20
	lbeq	lightpalthx
	cmp	#21
	lbeq	a2cpal
	cmp	#22
	lbeq	a2apal
	cmp	#23
	lbeq	a2fpal
	cmp	#24
	lbeq	citypal
	cmp	#25
	lbeq	spacepalthx
	cmp	#26
	lbeq	a2apal
	cmp	#27
	lbeq	a2bpal
	cmp	#28
	lbeq	spacepalthx
	cmp	#29
	lbeq	a2fpal
	cmp	#30
	lbeq	holepal
	cmp	#31
	lbeq	a2bpal
	cmp	#32
	lbeq	a2cpal
	cmp	#33
	lbeq	tbossmenupal
	cmp	#34
	lbeq	tbossmenupal
	cmp	#35
	lbeq	macbeth1
	cmp	#36
	lbeq	fxpinkcorn1
	cmp	#99
	lbeq	macbeth1
tbossmenupal
	dmacgram	0,0,(bgtbossvhpac),7*32		;Yes Background
	jmp	goon1
holepal
	dmacgram	0,0,(bgholepac),7*32		;Yes Background
	jmp	goon1
doabm
	dmacgram	0,0,(bgbmpac),7*32		;Yes Background
	jmp	goon1
yamapal
	dmacgram	0,0,(bgyamapac),7*32		;Yes Background
	jmp	goon1
howbouttm3
	dmacgram	0,0,(bgtm3pac),7*32		;Yes Background
	jmp	goon1
howbouttm2
	dmacgram	0,0,(bgtm2pac),7*32		;Yes Background
	jmp	goon1
a2cpal
	dmacgram	0,0,(bg2cpac),7*32		;Yes Background
	jmp	goon1
a2bpal
	dmacgram	0,0,(bg2bpac),7*32		;Yes Background
	jmp	goon1
a2apal
	dmacgram	0,0,(bg2apac),7*32		;Yes Background
	jmp	goon1
a2fpal
	dmacgram	0,0,(bg2fpac),7*32		;Yes Background
	jmp	goon1
lightpalthx
	dmacgram	0,0,(bglightpac),7*32		;Yes Background
	jmp	goon1
starspalthx
	dmacgram	0,0,(bgstarspac),7*32		;Yes Background
	jmp	goon1
spacepalthx
	dmacgram	0,0,(bgspacepac),7*32		;Yes Background
	jmp	goon1
a2dpal
	dmacgram	0,0,(bg2dpac),7*32		;Yes Background
	jmp	goon1
a2gpal
	dmacgram	0,0,(bg2gpac),7*32		;Yes Background
	jmp	goon1
vortexpal
	dmacgram	0,0,(bgvortexpac),7*32		;Yes Background
	jmp	goon1
citypal
	dmacgram	0,0,(bgcitypac),7*32		;Yes Background
	jmp	goon1
fxdescorn1
	dmacgram	0,0,(bgfxdespac),7*32		;Yes Background
	jmp	goon1
fxbluecorn1
	dmacgram	0,0,(bgfxbluepac),7*32		;Yes Background
	jmp	goon1
fxgreencorn1
	dmacgram	0,0,(bgfxgreenpac),7*32		;Yes Background
	jmp	goon1
fxpinkcorn1
	dmacgram	0,0,(bgfxpinkpac),7*32		;Yes Background
	jmp	goon1
sectork1x
	dmacgram	0,0,(bgnewspacepac),7*32		;Yes Background
	jmp	goon1
alphacorn1
	dmacgram	0,0,(bgcornpac),7*32		;Yes Background
	jmp	goon1
fortuna1
	dmacgram	0,0,(bgfortnpac),7*32		;Yes Background
	jmp	goon1
desert1
	dmacgram	0,0,(bgvortexpac),7*32		;Yes Background
	jmp	goon1
doblackout
	jsl	makebg2black_l
	jmp	goon1
macbeth1
	dmacgram	0,0,(bgmacbethpac),7*32		;Yes Background
goon1
	rtl
	
palfadetofxgreen_l	a8
	lda	fadepaltofxgreen
	bne	.fadeit
	rtl
.fadeit	
	cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltofxgreen
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadegreen,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadegreen,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadegreen,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
;	lda	pgbg
;	cmp	#4
;	bne	.no
	lda	#34
	sta	fadepaltofxblue
.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltofxgreen
	rtl

palfadetofxblue_l	a8
	lda	fadepaltofxblue
	bne	.fadeit
	rtl
.fadeit	
	cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltofxblue
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadeblue,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadeblue,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadeblue,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
;	lda	pgbg
;	cmp	#4
;	bne	.no
	lda	#34
	sta	fadepaltofxpink

.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltofxblue
	rtl
	
palfadetofxpink_l	a8
	lda	fadepaltofxpink
	bne	.fadeit
	rtl
.fadeit	
	cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltofxpink
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadepink,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadepink,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadepink,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
;	lda	pgbg
;	cmp	#4
;	bne	.no
	lda	#34
	sta	fadepaltofxdes

.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltofxpink
	rtl
	
palfadetofxdes_l	a8
	lda	fadepaltofxdes
	bne	.fadeit
	rtl
.fadeit	
	cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltofxdes
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadedes,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadedes,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadedes,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
;	lda	pgbg
;	cmp	#4
;	bne	.no
	lda	#34
	sta	fadepaltofxgreen

.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltofxdes
	rtl
	
	
	
	
palfadetoyamao_l	a8
	lda	fadepaltoyamao
	bne	.fadeit
	rtl
.fadeit		cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltoyamao
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadecorn,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadecorn,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadecorn,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
	lda	pgbg
	cmp	#7
	bne	.no
	lda	#34
	sta	fadepaltoyamab

.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltoyamao
	rtl
	
palfadetoyamab_l	a8
	lda	fadepaltoyamab
	bne	.fadeit
	rtl
.fadeit		cmp	#34
	lbeq	.decnexit
	dec	a
	sta	fadepaltoyamab
	
	ai16
	ldx	#0
	ldy	#0
	lda	#32
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadecity,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadecity,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadecity,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	a8
	lda	pgbg
	cmp	#7
	bne	.no
	lda	#34
	sta	fadepaltoyamao

.no
	a8
	IFEQ	1	;removed
	lda	pgbg
	cmp	#7
	beq	.palstuff
	cmp	#4
	bne	.nopalstuff
.palstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
.nopalstuff
	ENDC
	rtl
.decnexit
	dec	fadepaltoyamab
	rtl



palfadetocorn2_l	a8
	lda	fadepaltocorn2
	bne	.fadeit
	rtl
.fadeit		dec	a
	sta	fadepaltocorn2
	
	ai16
	ldx	#32
	ldy	#32
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadecorn2,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadecorn2,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadecorn2,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	rtl

palfadetocornnite_l	a8
	lda	fadepaltocornnite
	bne	.fadeit
	rtl
.fadeit		dec	a
	sta	fadepaltocornnite
	
	ai16
	ldx	#64
	ldy	#64
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadecornnite,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadecornnite,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadecornnite,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	rtl


palfaderandom_l	a8
	lda	fadepalrandom
	bne	.fadeit
	rtl
.fadeit	
	dec	a
	sta	fadepalrandom
	
	ai16
	ldx	palfrom
	ldy	palto
	lda	pallen
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
;	lda.l	fxfadecorn2,x
	jsl	random_l
	sta	tempcolor1
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
;	lda.l	fxfadecorn2,x
;	jsl	random_l
	lda	tempcolor1
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
;	lda.l	fxfadecorn2,x
;	jsl	random_l
	lda	tempcolor1
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	pla
	dec	a
	lbne	.lp
	lda	#33
	sta	fadepalrandom
	rtl

select_ship_l
;	jsr	select_ship
	jsl	setship
	rtl
select_ship
	phx
	phy
	a16
	and	#$00ff
	asl	a
	asl	a
	asl	a
	tax
 	
	lda.l	player_shapes,x
	sta.l	playershape
	lda.l	player_shapes+2,x
	sta.l	playershapeL
	lda.l	player_shapes+4,x
	sta.l	playershapeR
	lda.l	player_shapes+6,x
	sta.l	playershapeLR

	a8
	ply
	plx
	rts

playerstart_init_l
	a8
	s_set_alvar	W,x,alx_frame,#0
	stz			fastend
	lda	newgameplus
	bne	.onlytwo
	s_set_var	W,specwepcntone,#5
	s_set_var	W,specwepcnttootemp,#5
	s_set_var	W,specwepcntthreetemp,#5
	s_set_var	W,specwepcntfourtemp,#5
	s_set_var	W,specwepcntfivetemp,#5
	bra	.donebomb
.onlytwo
	s_set_var	W,specwepcntone,#2
	s_set_var	W,specwepcnttootemp,#2
	s_set_var	W,specwepcntthreetemp,#2
	s_set_var	W,specwepcntfourtemp,#2
	s_set_var	W,specwepcntfivetemp,#2
.donebomb
	stz	speccnttwo
	stz	speccntthree
	stz	speccntfour
	stz	speccntfive
	s_set_var	B,pshipflags,#0
	s_set_var	B,pshipflags2,#0
	s_set_var	B,pshipflags3,#0
	stz	teamshots
	stz	twoplayer
;	stz	playertwoready
	lda.l	m_playertwoactivated
	beq	.notwoplayer
	lda	livestwo
	beq	.notwoplayer
;	lda	#10
;	sta	playertwoready
	s_set_objtobeplayer	y
	s_clr_alsflag	y,invisible
	lda	ponedead
	beq	.notwoplayer
	s_set_alsflag	x,invisible
	s_set_alsflag	x,colldisable
	lda	lives
	beq	.notwoplayer
	bmi	.notwoplayer
	lda	#0
	sta.l	m_playeronedead
	stz	ponedead
	s_clr_alsflag	x,invisible
	s_clr_alsflag	x,colldisable
	
	
.notwoplayer	
	lda	#0
	sta.l	m_damagetwo		;reset player 2 health
	lda	scored
	and	#1
	cmp	#0
	beq	.skipthescore
	a16
	lda.l	playerscoretemp
	sta.l	playerscore
	a8
.skipthescore
	stz	debugalien
	stz	weaponnumberpone
	stz	weaponnumberptwo

	stz	weapptr
	stz	weapnextptr

	stz	helpshots
	stz	shieldup
	lda	superspeeddelay
	cmp	#ktest
	beq	.noimdone3pointer
	cmp	#ktest3
	beq	.noimdone3pointer
	cmp	#ktest4
	beq	.noimdone3pointer
	cmp	#ktest5
	beq	.noimdone3pointer
	a16
	lda	cockpitmode
	bne	.cockpit
	lda	curr_ship
	cmp	#7
	bmi	.maybe
	bra	.maybe25
.noimdone3pointer
	jmp	.noimdone3
.cockpit
	a8
	s_set_var    W,viewdist,#30
	s_set_var    W,outviewdist,#30
	s_set_var    W,outdist,#30
	bra	.noimdone3
.maybe25
	a8
	s_set_var    W,viewdist,#170					;zoom for new ships
	s_set_var    W,outviewdist,#170
	s_set_var    W,outdist,#170
	bra	.noimdone3
.maybe
	a8
	lda	shpmode
	beq	.normalview
	s_set_var    W,viewdist,#160
	s_set_var    W,outviewdist,#160
	s_set_var    W,outdist,#160
	bra	.noimdone3
	
.normalview
	s_set_var    W,viewdist,#120
	s_set_var    W,outviewdist,#120
	s_set_var    W,outdist,#120
.noimdone3

	lda	curr_ship
	beq	.nochange
	bra	.keepthesame
.nochange
;	lda	#pshipnum_norm
;	sta	curr_ship
.keepthesame
	jsl	select_ship_l
	jsl	setship
	rtl




palfadetonewspace1_l	a8
	lda	fadepalrb1
	bne	.fadeit
	rtl
.fadeit
	cmp	#34
	lbeq	.decnexit
		dec	a
	sta	fadepalrb1
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadenewspace1,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadenewspace1,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadenewspace1,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8
	lda	#34
	sta	fadepalrb2
	a8
	lda	stopcounting
	beq	.nopalstuff
	IFEQ	1	;removed
	lda	pgbg
	cmp	#2
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
	ENDC
.nopalstuff
	rtl
.decnexit
	dec	fadepalrb1
	rtl
	
palfadetonewspace2_l	a8
	lda	fadepalrb2
	bne	.fadeit
	rtl
.fadeit		
	cmp	#34
	lbeq	.decnexit

	dec	a
	sta	fadepalrb2
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadenewspace2,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadenewspace2,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadenewspace2,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8
	lda	#34
	sta	fadepalrb3
	a8
	lda	stopcounting
	beq	.nopalstuff
	IFEQ	1	;removed
	lda	pgbg
	cmp	#2
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
	ENDC
.nopalstuff
	rtl
.decnexit
	dec	fadepalrb2

	rtl
	
palfadetonewspace3_l	a8
	lda	fadepalrb3
	bne	.fadeit
	rtl
.fadeit	
	cmp	#34
	lbeq	.decnexit

	dec	a
	sta	fadepalrb3
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadenewspace3,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadenewspace3,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadenewspace3,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8
	lda	#34
	sta	fadepalrb4
	a8
	lda	stopcounting
	beq	.nopalstuff
	IFEQ	1	;removed
	lda	pgbg
	cmp	#2
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
	ENDC
.nopalstuff
	rtl

.decnexit
	dec	fadepalrb3
	rtl
	
palfadetonewspace4_l	a8
	lda	fadepalrb4
	bne	.fadeit
	rtl
.fadeit
	cmp	#34
	lbeq	.decnexit

		dec	a
	sta	fadepalrb4
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadenewspace4,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadenewspace4,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadenewspace4,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8
	lda	#34
	sta	fadepalrb5
	a8
	lda	stopcounting
	beq	.nopalstuff
	IFEQ	1	;removed
	lda	pgbg
	cmp	#2
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
	ENDC
.nopalstuff
	rtl
.decnexit
	dec	fadepalrb4
	rtl
	
palfadetonewspace5_l	a8
	lda	fadepalrb5
	bne	.fadeit
	rtl
.fadeit
	cmp	#34
	lbeq	.decnexit

		dec	a
	sta	fadepalrb5
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	fxfadenewspace5,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	fxfadenewspace5,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	fxfadenewspace5,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8
	lda	#34
	sta	fadepalrb1
	a8
	lda	stopcounting
	beq	.nopalstuff
	IFEQ	1	;removed
	lda	pgbg
	cmp	#2
	bne	.nopalstuff
	dmacgram	0,0,pal0palette,8*32		;DMA palette 0-7
	ENDC
.nopalstuff
	rtl
.decnexit
	dec	fadepalrb5
	rtl

palfadetotitle_l	a8
	lda	fadepaltitle
	bne	.fadeit
	rtl
.fadeit
	dec	a
	sta	fadepaltitle
	
	ai16
	ldx	#96
	ldy	#96
	lda	#64
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	titlepalette,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	titlepalette,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	titlepalette,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8 ; 1.10.01 bugfix
	rtl
	
palfadetoblack_l	a8
	lda	fadepalblack
	bne	.fadeit
	rtl
.fadeit
	dec	a
	sta	fadepalblack
	
	ai16
	ldx	palfrom
	ldy	palto
	lda	pallen
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda	#0
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda	#0
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda	#0
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8 ; 1.10.01 bugfix
	rtl


palfadetoOOTD_l	a8
	lda	fadepalootd
	bne	.fadeit
	rtl
.fadeit
	dec	a
	sta	fadepalootd
	
	ai16
	ldx	palfrom
	ldy	palto
	lda	pallen
.lp
	pha
	lda.w	pal0palette,y
	and	#%111110000000000
	sta	tpa
	lda.l	spacepalette,x
	and	#%111110000000000
	cmp	tpa
	beq	.skipb
	bcs	.incb
.decb	lda	tpa
	sec
	sbc	#%000010000000000
	bra	.skipb
.incb	lda	tpa
	clc
	adc	#%000010000000000
.skipb	sta	tpx

	lda.w	pal0palette,y
	and	#%1111100000
	sta	tpa
	lda.l	spacepalette,x
	and	#%1111100000
	cmp	tpa
	beq	.skipg
	bcs	.incg
.decg	lda	tpa
	sec
	sbc	#%0000100000
	bra	.skipg
.incg	lda	tpa
	clc
	adc	#%0000100000
.skipg	sta	tpy

	lda.w	pal0palette,y
	and	#%11111
	sta	tpa
	lda.l	spacepalette,x
	and	#%11111
	cmp	tpa
	beq	.skipr
	bcs	.incr
.decr	lda	tpa
	dec	a
	bra	.skipr
.incr	lda	tpa
	inc	a
.skipr	ora	tpx
	ora	tpy
	sta.w	pal0palette,y

	iny
	iny
	inx
	inx
	
	pla
	dec	a
	lbne	.lp
	a8 ; 1.10.01 bugfix
	rtl
	
setrandshape
	ai16
.again
	jsl	random_l
	and	#127
	beq	.ok
	cmp	#7
	bmi	.again
	cmp	#shipcount
	bpl	.again
.ok
	asl	a
	phx
	tax
	lda.l	shiplistshape,x
	plx
	sta.w	al_shape,x
	rtl
	
	
settoblackbg
	decvramnotrans		0,vchr_logback,bgasteroidccr,6*k			;blank stuff
	decbg2vramnotrans	0,vsc_base2,bgblankpcr,8*k				;blank stuff
	jsl	makebg2black_l
	dmacgram	0,0,(bgmacbethpac),7*32		;Yes Background
	rtl
	
;------------------------------------------------	
estrat_istrat
	s_start_strat
	s_set_alptrs	x,estrat_strat,0,0
	s_clr_alsflag	x,collide
	s_set_alsflag	x,colldisable
	s_set_alsflag	x,nohitaffect
	s_set_alvar		B,x,al_roty,#deg180
	s_sub_alvar		W,x,al_worldz,#50
	
estrat_strat
	s_start_strat
	s_add_playerz	x					;add z distance traveled by player to this object
	s_jmp_alvarMOREeq	W,x,al_worldx,#40,.done
	s_add_alvar		W,x,al_worldx,#2
	s_add_alvar		B,x,al_rotx,#2
	s_add_alvar		B,x,al_roty,#5
	s_sub_alvar		B,x,al_rotz,#5
	s_set_alvar		B,x,al_sbyte1,#30
	s_end_strat
.done
	s_set_alvar		W,x,al_worldx,#41
	s_achase_alvar	B,x,al_rotx,#0,3
	s_achase_alvar	B,x,al_roty,#deg180,3
	s_achase_alvar	B,x,al_rotz,#0,3
	s_decbne_alvar	B,x,al_sbyte1,.nodonedec
	a8
	lda	tempvar8
	ora	#1
	sta	tempvar8	
.nodonedec
	s_end_strat
;------------------------------------------------	
xstrat_istrat
	s_start_strat
	s_set_alptrs	x,xstrat_strat,0,0
	s_clr_alsflag	x,collide
	s_set_alsflag	x,colldisable
	s_set_alsflag	x,nohitaffect
	s_set_alvar		B,x,al_roty,#deg180	
	s_sub_alvar		W,x,al_worldz,#50
xstrat_strat
	s_start_strat
	s_add_playerz	x					;add z distance traveled by player to this object
	s_jmp_alvareq	W,x,al_worldy,#-30,.done
	s_jmp_alvareq	W,x,al_worldy,#-31,.done
	s_set_alvar		B,x,al_sbyte1,#30
	s_sub_alvar		W,x,al_worldy,#2
	s_sub_alvar		B,x,al_rotx,#7
	s_sub_alvar		B,x,al_roty,#2
	s_sub_alvar		B,x,al_rotz,#10
	s_end_strat
.done
	s_set_alvar		W,x,al_worldy,#-31
	s_achase_alvar	B,x,al_rotx,#0,3
	s_achase_alvar	B,x,al_roty,#deg180,3
	s_achase_alvar	B,x,al_rotz,#0,3
	s_decbne_alvar	B,x,al_sbyte1,.nodonedec
	a8
	lda	tempvar8
	ora	#2
	sta	tempvar8
.nodonedec
	s_end_strat

fire_eggie				; relative to player speed.
.again
	s_jmp_random	.1,10
	s_jmp_random	.2,10
	s_jmp_random	.3,10
	s_jmp_random	.4,10
	s_jmp_random	.5,10
	jmp	.again
.5
	s_make_obj		#egg,.badobj
	bra	.done
.1	s_make_obj		#egggreen,.badobj
	bra	.done
.2	s_make_obj		#eggblue,.badobj
	bra	.done
.3	s_make_obj		#eggyellow,.badobj
	bra	.done
.4	s_make_obj		#eggblack,.badobj
	;bra	.done



.done
	s_sprite_obj		y,#0
	s_set_aldata		y,#1,#8
	s_set_alptrs		y,relflatmiss_Istrat,weapcollide_Istrat,remove_Istrat
	s_set_speed		y,#60
	s_set_lifecnt		y,#80
	s_set_colltype		y,enemyweap
	s_set_colltype		y,laser
	s_set_alsflag		y,relexplode
	jsl			gen_weapon_l
	jsl			enemybattrysound_l
.badobj	rtl

calibrationmenu					
;-------------------------------------------------
	a8
	lda	#1
	sta	calibscr
	jsl	scrollthebg
	lda	#0
	sta.l	m_clrbitmaps

	lda	mousemode
	lbne	.mousejump1
	
	lda	scope_new+1
	and	#$40
	beq	.nocalib	
;calibration
	lda	#$8A				;center H
	sec
	sbc	scope_h
	sta	scope_h_offset	
	lda	#$62				;center V
	sec
	sbc	scope_v
	sta	scope_v_offset
	lda	#1
	sta	calibrated
;end calibration
.nocalib

	a8
	lda	scope_held+1
	and	#$80
	lbeq	.noshot
	
	lda	scope_h
	clc
	adc	scope_h_offset
	sta	scope_h_final

	lda	scope_h_final
	sec
	sbc	#$8A
	sta	htotal

;----
	a8
	lda	scope_v
	clc
	adc	scope_v_offset
	sta	scope_v_final

	lda	scope_v_final
	sec
	sbc	#$53
	sta	vtotal

;----now draw an object
	a8

	lda	#108
	clc
	adc	htotal
	sta.l	m_vanishx
	
	lda	#76
	clc
	adc	vtotal
	sta.l	m_vanishy

	a16

	lda	currcolor
	asl	a
	tax
	lda.l	targetlist,x
	sta	foxy_shape
	lda	currsize
	sta.l	m_bigz

.noshot
	IFEQ	1				;debug data, commented out
	settext	0,0
	a16
	lda	scope_h_offset
	jsl	printw_l

	settext	0,1
	a16
	lda	htotal
	jsl	printw_l

	settext	0,2
	a16
	lda	scope_v_offset
	jsl	printw_l
	
	settext	0,3
	a16
	lda	vtotal
	jsl	printw_l
	ENDC
.noscopev	

	lda	cockpitmode		;check if select has been hit
	lbne	.notextcleared
;-----calibrate instructions----
	a8
	settext	0,0
	showtext	calibrateheretext
	
	settext	0,1
	showtext	selecttocleartext
.mousejump1
;---------START GAME------	
	a8
	lda	#$FF
	sta	hilite
	sta	hilite+1
	settext	4,22
	showtxt	menustartgametext
	a8
	stz	hilite
	stz	hilite+1
	lda	#0
	sta.l		m_clrbitmaps		
.notextcleared

;----Color Display-------
	a8
	settext	0,21
	showtext	colortext
	settext	7,21
	printvar	currcolor

;-----size-------

	a8
	settext	11,21
	showtext	sizetext
	settext	16,21
	a16
	lda.l	currsize
	jsl	printw_l

;------------color change------------
	a16
	TESTJOYPAD	A
	beq		nocolorchange1
	lda	trig0
	bit	#pad_a
	beq		nocolorchange1
	lda	currcolor
	cmp	#5		;last entry of target color list (max entries)
	beq	.resetcolor
	inc	currcolor
	bra	nocolorchange1
	
.resetcolor
	stz	currcolor

nocolorchange1


	a16
	TESTJOYPAD	b
	beq		nocolorchange2
	lda	trig0
	bit	#pad_b
	beq		nocolorchange2
	lda	currcolor
	cmp	#0
	beq	.resetcolor2
	dec	currcolor
	bra	nocolorchange2
	
.resetcolor2
	lda	#5			;last entry of target color list (max entries)
	sta	currcolor

nocolorchange2


;---------size change--------

	a16
	TESTJOYPAD	TLEFT,cont0l
	beq		nosizedown
	lda	trig0
	bit	#pad_tleft
	beq		nosizedown
	lda	currsize
	beq	nosizedown
	sec
	sbc	#50
	sta	currsize
nosizedown

	TESTJOYPAD	TRIGHT,cont0l
	beq		nosizeup
	lda	trig0
	bit	#pad_tright
	beq		nosizeup
	lda	currsize
	cmp	#3000
	beq	nosizeup
	clc
	adc	#50
	sta	currsize
nosizeup

;--------select - clear------------------
	a16
	TESTJOYPAD	SELECT
	beq	noclearscr
	lda	trig0
	bit	#pad_select
	beq	noclearscr
	a8
	lda	#1
	sta.l	m_clrbitmaps
	sta		cockpitmode
	
	
	
noclearscr
;---------start - exit-------------------
	a16
	TESTJOYPAD	START
	beq		noexit2xa
	lda	trig0
	bit	#pad_start
	beq		noexit2xa
	a8
	stz	stopcounting
	jml	restart
	
noexit2xa
	rtl


;-----------------------------------------------	
;-----------------------------------------------	
;-----------------------------------------------	
;				START THANKS PAGE
;-----------------------------------------------	
;-----------------------------------------------	
;-----------------------------------------------		
thanksmenu					
	stz	foxy_ptr				
	stz	foxy_shape				
								
	jsl	scrollthebg								
;-------------------------------------------------

;-----------SPECIAL MENU TITLE-----------
	settext	0,0
	showtxt	thanks1
	showtxt	thanks2
	showtxt	thanks3
	lda	#0
	sta.l	m_clrbitmaps
	
;---------PREV PAGE------	
	lda	menuselected
	cmp	#0
	bne	nohilite1222xa6

	lda	#$FF
	sta	hilite
	sta	hilite+1
nohilite1222xa6
	settext	4,21
parentlabel6x
	showtxt	menupreviouspagetext

	stz	hilite
	stz	hilite+1
	lda	#0
	sta.l		m_clrbitmaps		

;---------PRESS START TO EXIT TEXT------	
	lda	menuselected
	cmp	#1
	lbne	nohilite12222x5

	lda	#$FF
	sta	hilite
	sta	hilite+1
nohilite12222x5
	settext	4,22
	showtxt	menustartgametext

	stz	hilite
	stz	hilite+1
	lda	#0
	sta.l		m_clrbitmaps	
;--------------------------
;---------SELECT-----------------
	
	TESTKEYDOWN	SELECT
	beq	.noselect3
	lda	trig0
	bit	#pad_SELECT
	beq	.noselect3
	jmp	select3


.noselect3

;---------DOWN-----------------
	TESTKEYDOWN	DOWN
	beq	nodownn2x
	lda	trig0
	bit	#pad_down
	beq	nodownn2x
select3
	a8
	trigse	9
	a16
	lda	menuselected
	cmp	#1				;Max number of items on menu -1
	bpl	top2x
	inc	menuselected
	bra	downpt22x
top2x
	stz	menuselected
downpt22x

nodownn2x


;----------UP--------------------
	TESTKEYDOWN	UP
	beq	noupp2x
	lda	trig0
	bit	#pad_up
	beq	noupp2x
	a8
	trigse	9
	a16
	lda	menuselected
	beq	bottom2x				;Don't go lower than 0, go to the bottom
	dec	menuselected
	bra	uppart22x
bottom2x
	lda	#1				;Last item on list (same as above)
	sta	menuselected
uppart22x

noupp2x

;---------start - exit-------------------
	a16
	TESTJOYPAD	START
	beq		noexit2x
	lda	trig0
	bit	#pad_start
	beq		noexit2x

	lda	menuselected
	cmp	#0
	beq	page2
	cmp	#1
	bne	noexit2x

	a8
	lda	scopemode
	beq	.noscope
	lda	calibrated
	bne	.noscope
	a8
	lda	pgbg
	sta	pgbgtemp
	lda	#99
	sta	pgbg
	lda	#5
	sta	stopcounting			;set STOPCOUNTING to a value of 5
	lda	#1
	sta.l		m_clrbitmaps
	stz	menuselected
	lda	#1
	sta	keyrdown
;	bgm2	kandojingle		
;	startbgm	10
.noscopeforyou
	jml	foxy_continue_l
	
.noscope
	stz	stopcounting
	jml	restart
	
page2
	a8
	lda	#2
	sta	stopcounting
	lda	#3					;page number
	sta	pagenumber			
	lda	#4					;position of THANKS on page 3
	sta	menuselected
	lda	#1
	sta.l	m_clrbitmaps
	jml	foxy_continue_l
	
noexit2x
	rtl



;---------------------------------------------
;---------------------------------------------
;---------------------------------------------
;---------------------------------------------

makeengine_srou_l
	s_make_obj	#boostshape,.bad

	phx
	phy
	a16
	ldy		al_shape,x
	tyx
	lda.l		sh_Zmax,x
	nega
	sta		svar_word2
	lda.l		sh_Ymax,x
	sec
	sbc		#24
	sta		svar_word1
	ply
	plx
	a8
	
	s_sprite_obj		y,#0,svar_word1
	s_set_alvar		B,y,al_relposz,svar_word2

	A16
	TYA	
	STA.L			ALX_FIREOBJPTR,X
	A8

	s_set_alsflag		y,colldisable
	jsl			updateengine_srou_l
	s_set_alsflag		y,invisible
	s_set_alflag		x,onfire
	
.bad	rtl


;-------------------CROSSHAIR MENU-----------
;-------------------CROSSHAIR MENU-----------
;-------------------CROSSHAIR MENU-----------
;-------------------CROSSHAIR MENU-----------
;-------------------CROSSHAIR MENU-----------

xhairmenu					
;-------------------------------------------------
	a8
	jsl	scrollthebg

;-----Crosshair Type----
	lda	menuselected
	cmp	#0
	bne	.nohi2
	lda	#$FF
	sta	hilite
	sta	hilite+1
.nohi2
	settext	0,0
	showtext	Crosshairtypetext
	stz	hilite
	stz	hilite+1
	
	settext	19,0
	lda	nocrosshairpls
	beq	.orig
	cmp	#1
	beq	.off
	cmp	#2
	beq	.new
	
.orig
	showtext	menuorigtext
	bra	.mousejump1

.off
	showtext	offtext
	bra	.mousejump1

.new
	showtext	menunewtext
	
	
.mousejump1
;---------Crosshair Shape------	
;	lda	nocrosshairpls
;	cmp	#2
;	bne	.noch
	lda	menuselected
	cmp	#1
	bne	.nohix
	lda	#$FF
	sta	hilite
	sta	hilite+1
.nohix
	settext	0,1
	showtxt	crosshairshapetext
	a8
	stz	hilite
	stz	hilite+1
	settext	19,1
	lda	tempplayernum
	cmp	#2
	beq	.2
	cmp	#3
	beq	.3
	cmp	#4
	beq	.4
	cmp	#5
	beq	.5
	printvar	currxhair
	bra	.donn
.2
	printvar	currxhair2
	bra	.donn
.3
	printvar	currxhair3
	bra	.donn
.4
	printvar	currxhair4
	bra	.donn
.5
	printvar	currxhair5
;	bra	.donn


.donn
	showtext	blankspace
	

;---------Current Player------	
;	lda	nocrosshairpls
;	cmp	#2
;	bne	.noch
	lda	menuselected
	cmp	#2
	bne	.nohixx
	lda	#$FF
	sta	hilite
	sta	hilite+1
.nohixx
	settext	0,2
	showtxt	currplayertext
	a8
	stz	hilite
	stz	hilite+1
	settext	19,2
	printvar	tempplayernum
.noch

;---------PREVIOUS PAGE------	
	lda	menuselected
	cmp	#3
	bne	.nohi
	lda	#$FF
	sta	hilite
	sta	hilite+1
.nohi
	settext	4,22
	showtxt	menupreviouspagetext
	stz	hilite
	stz	hilite+1	
.notextcleared



;---------DOWN-----------------
	a16
	TESTKEYDOWN	DOWN
	beq	nodownn2x321
	lda	trig0
	bit	#pad_down
	beq	nodownn2x321

	a8
	trigse	9
	a16
	lda	menuselected
	cmp	#3				;Max number of items on menu
	bpl	top2x123
	inc	menuselected
	bra	downpt22x123
top2x123
	stz	menuselected
downpt22x123

nodownn2x321


;----------UP--------------------
	a16
	TESTKEYDOWN	UP
	beq	noupp2x123
	lda	trig0
	bit	#pad_up
	beq	noupp2x123
	a8
	trigse	9
	a16
	lda	menuselected
	beq	bottom2x321				;Don't go lower than 0, go to the bottom
	dec	menuselected
	bra	uppart22x321
bottom2x321
	lda	#3				;Last item on list (same as above)
	sta	menuselected
uppart22x321

noupp2x123


;----------RIGHT------------
	a16
	TESTKEYDOWN	RIGHT
	lbeq	norightt4u
	lda	trig0
	bit	#pad_right
	lbeq	norightt4u
	a8
	lda	menuselected
	cmp	#0
	beq	.0
	cmp	#1
	lbeq	.1
	cmp	#2
	lbeq	.2
	jmp	norightt4u

.0
	a16
	lda	nocrosshairpls
	cmp	#2
	beq	.goto0
	inc	nocrosshairpls
	lda	#1
	sta.l	m_clrbitmaps
	lda	nocrosshairpls
	cmp	#2
	lbmi	norightt4u.noshaper
	jmp		norightt4u.showthexhair
;	jmp	norightt4u
.goto2
	lda	#2
	sta	nocrosshairpls
	lda	tempplayernum
	cmp	#1
	lbeq	norightt4u.1d
	cmp	#2
	lbeq	norightt4u.2d
	cmp	#3
	lbeq	norightt4u.3d
	cmp	#4
	lbeq	norightt4u.4d
	cmp	#5
	lbeq	norightt4u.5d

	jmp	norightt4u
.goto0
	stz	nocrosshairpls
	lda	#xhairtot
	asl	a
	tax
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.1
	a16
	lda	nocrosshairpls
	cmp	#2
	lbmi	norightt4u
	
	lda	tempplayernum
	cmp	#1
	beq	.p1
	cmp	#2
	beq	.p2
	cmp	#3
	lbeq	.p3
	cmp	#4
	lbeq	.p4
	cmp	#5
	lbeq	.p5
	

.p1
	a16
	lda	currxhair
	cmp	#xhairtot-1
	bpl	.goto0again
	inc	currxhair
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.goto0again
	stz	currxhair
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.p2
	a16
	lda	currxhair2
	cmp	#xhairtot-1
	bpl	.goto0again2
	inc	currxhair2
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair2
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.goto0again2
	stz	currxhair2
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair2
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u

.p3
	a16
	lda	currxhair3
	cmp	#xhairtot-1
	bpl	.goto0again3
	inc	currxhair3
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair3
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.goto0again3
	stz	currxhair3
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair3
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u

.p4
	a16
	lda	currxhair4
	cmp	#xhairtot-1
	bpl	.goto0again4
	inc	currxhair4
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair4
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.goto0again4
	stz	currxhair4
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair4
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u

.p5
	a16
	lda	currxhair5
	cmp	#xhairtot-1
	bpl	.goto0again5
	inc	currxhair5
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u

	lda	currxhair5
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.goto0again5
	stz	currxhair5
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair5
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u





.2
	a16
	lda	multitapmode
	beq	.2playerstf
	lda	numplayers
	cmp	#1
	beq	.spec
	lda	tempplayernum
	cmp	numplayers
	bpl	.resetitto1
	inc	tempplayernum
	bra	.donenowdoshape
.2playerstf
	lda	playertwoactivated
	lbeq	norightt4u
	lda	tempplayernum
	cmp	#2
	beq	.resetitto1
	inc	tempplayernum
	jmp	norightt4u

.spec
	lda	tempplayernum
	cmp	#5
	beq	.resetitto1
	inc	tempplayernum
	bra	.donenowdoshape
.resetitto1
	lda	#1
	sta	tempplayernum
.donenowdoshape
	lda	tempplayernum
	cmp	#1
	beq	.sh1
	cmp	#2
	beq	.sh2
	cmp	#3
	beq	.sh3
	cmp	#4
	beq	.sh4
	cmp	#5
	lbeq	.sh5
.sh1
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.sh2
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair2
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.sh3
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair3
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.sh4
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair4
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
.sh5
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	norightt4u
	lda	currxhair5
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	norightt4u
	
norightt4u






;----------LEFT------------
	a16
	TESTKEYDOWN	LEFT
	lbeq	noleftt4u
	lda	trig0
	bit	#pad_left
	lbeq	noleftt4u
	a8
	lda	menuselected
	cmp	#0
	beq	.0
	cmp	#1
	lbeq	.1
	cmp	#2
	lbeq	.2
	jmp	noleftt4u

.0
	a16
	lda	nocrosshairpls
	beq	.goto2
	dec	nocrosshairpls
	lda	#1
	sta.l	m_clrbitmaps
	lda	nocrosshairpls
	cmp	#2
	bmi	.noshaper
	jmp	noleftt4u
.goto2
	lda	#2
	sta	nocrosshairpls
.showthexhair	LOCAL
	lda	tempplayernum
	cmp	#1
	beq	.1d
	cmp	#2
	beq	.2d
	cmp	#3
	beq	.3d
	cmp	#4
	beq	.4d
	cmp	#5
	beq	.5d

.1d	LOCAL
	a16
	lda	currxhair
.rest
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u	

.2d	LOCAL
	a16
	lda	currxhair2
	bra	.rest
.3d	LOCAL
	a16
	lda	currxhair3
	bra	.rest
.4d	LOCAL
	a16
	lda	currxhair4
	bra	.rest
.5d	LOCAL
	a16
	lda	currxhair5
	bra	.rest



.noshaper	LOCAL
	a16
	lda	#xhairtot
	asl	a
	tax
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	jmp	noleftt4u
	
	
	
.1
	a16
	lda	nocrosshairpls
	cmp	#2
	lbmi	noleftt4u

	lda	tempplayernum
	cmp	#1
	beq	.p1x
	cmp	#2
	beq	.p2x
	cmp	#3
	lbeq	.p3x
	cmp	#4
	lbeq	.p4x
	cmp	#5
	lbeq	.p5x
	

.p1x
	a16
	lda	currxhair
	cmp	#0
	beq	.gotolast
	dec	currxhair
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair
.restofx
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
.gotolast
	a16
	lda	#xhairtot-1
	sta	currxhair
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair
	bra	.restofx
	
.p2x
	a16
	lda	currxhair2
	beq	.gotolast2
	dec	currxhair2
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair2
	jmp	.restofx
.gotolast2
	lda	#xhairtot-1
	sta	currxhair2
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair2
	jmp	.restofx
	
	
.p3x
	a16
	lda	currxhair3
	beq	.gotolast3
	dec	currxhair3
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair3
	jmp	.restofx
.gotolast3
	lda	#xhairtot-1
	sta	currxhair3
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair3
	jmp	.restofx
	
.p4x
	a16
	lda	currxhair4
	beq	.gotolast4
	dec	currxhair4
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair4
	jmp	.restofx
.gotolast4
	lda	#xhairtot-1
	sta	currxhair4
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair4
	jmp	.restofx


.p5x
	a16
	lda	currxhair5
	beq	.gotolast5
	dec	currxhair5
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair5
	jmp	.restofx
.gotolast5
	lda	#xhairtot-1
	sta	currxhair5
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair5
	jmp	.restofx




.2
	a16
	lda	multitapmode
	beq	.2players
	lda	numplayers
	cmp	#2
	bmi	.spec
	lda	tempplayernum
	cmp	#1
	beq	.resetittomax
	dec	tempplayernum
	bra	.donenowdoshape
.spec
	lda	multitapmode
	lbeq	noleftt4u
	lda	tempplayernum
	cmp	#1
	beq	.resetitto5
	dec	tempplayernum
	bra	.donenowdoshape
.resetittomax
	lda	numplayers
	sta	tempplayernum
	bra	.donenowdoshape
.2players
	lda	playertwoactivated
	lbeq	noleftt4u
	lda	tempplayernum
	cmp	#1
	beq	.goto2x
	dec	tempplayernum
	jmp	noleftt4u
.goto2x
	lda	#2
	sta	tempplayernum
	jmp	noleftt4u

.resetitto5
	lda	#5
	sta	tempplayernum
.donenowdoshape	
	lda	tempplayernum
	cmp	#1
	beq	.sh1
	cmp	#2
	beq	.sh2
	cmp	#3
	beq	.sh3
	cmp	#4
	lbeq	.sh4
	cmp	#5
	lbeq	.sh5
.sh1
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
.sh2
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair2
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
.sh3
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair3
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
.sh4
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair4
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
.sh5
	a16
	lda	nocrosshairpls
	cmp	#2
	lbne	noleftt4u
	lda	currxhair5
	asl	a
	tax
	stx	foxy_ptr
	lda.l	xhairlist,x
	sta	foxy_shape
	a8
	lda	#1
	sta.l	m_clrbitmaps
	jmp	noleftt4u
	
noleftt4u
;;-----L Trigger

	a16
	TESTJOYPAD	TLEFT,cont0l
	beq		notleft
	lda	trig0
	bit	#pad_tleft
	beq		notleft
	lda.l	m_bigz
	cmp	#51
	bmi	notleft
	sec
	sbc	#25
	sta.l	m_bigz
	lda	#1
	sta.l	m_clrbitmaps

notleft
;;-----R Trigger

	a16
	TESTJOYPAD	TRIGHT,cont0l
	beq		notright
	lda	trig0
	bit	#pad_tright
	beq		notright
	lda.l	m_bigz
	cmp	#500
	bpl	notright
	clc
	adc	#25
	sta.l	m_bigz
	lda	#1
	sta.l	m_clrbitmaps

notright
;---------start - exit-------------------
	a16
	TESTJOYPAD	START
	beq		noexit2xaff
	lda	trig0
	bit	#pad_start
	beq		noexit2xaff
	lda	menuselected
	cmp	#3					;position of PREVIOUS PAGE
	bne	noexit2xaff
	a8
	lda	#2
	sta	stopcounting
	lda	#3					;page number
	sta	pagenumber			
	lda	#1					;position of CROSSHAIR on page 3
	sta	menuselected
	a16
	lda	#0
	sta	foxy_shape
	a8
	stz	foxy_ptr
	lda	#1
	sta.l	m_clrbitmaps
	lda	pgbgtemp
	sta	pgbg
	jml	foxy_continue_l	
noexit2xaff
;	lda	menuselected
;	cmp	#1
;	bne	.normie
	lda	nocrosshairpls
	cmp	#2
	bne	.okiesthx
	lda	#1
	sta.l	m_clrbitmaps
	jsl	doanimation
;	bra	.okiesthx
;.normie
;	lda	#0
;	sta.l	m_clrbitmaps
.okiesthx
	rtl

loaddata
	a16
	loadmem
	sta	superfx2
	sta	m_clsr ; SUNLITFIX make sure chip speed is applied as desired after pregame menu

	loadmem
	sta	nobgmode
		
	
	loadmem
	sta	newgameplus
	
	loadmem
	sta	godmode
	
	loadmem	
	sta	randomfire
	
	loadmem	
	sta	scored
	
	loadmem	
	sta	pepperskip
	
	loadmem
	sta	endurance			;8
	
	loadmem
	sta	levelfeatures
	
	loadmem
	sta	enemy_firing		
	
	loadmem
	sta	rainbowlaser
	
	loadmem
	sta	bigheadmode
	
	loadmem
	sta.l	m_bigheadmode
	
	loadmem
	sta.l	m_biggerheadmode
	
	loadmem
	sta	skipscramble
	
	loadmem
	sta	rapidfire			;16
	
	loadmem
	sta	firerate	
	
	loadmem
	sta	darkmode
	
	loadmem
	sta	mistmode
	
	loadmem
	sta	palnumber
	
	loadmem
	sta	strat_valid
	
	loadmem
	sta	pweptemp
	
	loadmem
	sta	bgmspeed
	
	loadmem
	sta	curr_ship		;24
	
	loadmem
	sta	showcolbox
	
	loadmem
	sta	nanmode
	
	loadmem
	sta	wiremode
	

	loadmem
	sta	fpscounteron
	
	loadmem
	sta	bouncedeath		
	
	loadmem
	sta	nocrosshairpls
	
	loadmem
	sta	noborders
	
	loadmem
	sta	doboostmeter
	
	loadmem
	sta.l	m_wobblemode	;32
	
	loadmem
	sta	newcamera
	
	loadmem
	sta	playerW_HP
	
	loadmem
	sta	playerB_HP
	
	loadmem				
	sta	classichp
	
	loadmem
	sta	barrelroll
	
	loadmem
	sta	noenginemode
	
	loadmem
	sta	hilitecolor
	
	loadmem				;40
	sta	bgmsfx
	
	loadmem
	sta	dotsstars
	
;	loadmem
;	sta	craymode
	
	loadmem
	sta	randomsound
	
	loadmem
	sta	randombgm		
	
;	loadmem
;	sta	kandomode
	
	loadmem
	sta	randompos
	
	loadmem
	sta	viewshit
	
;	loadmem
;	sta	cursedbgm			;48
	
	loadmem
	sta	cursedopen
	
;	loadmem
;	sta	kandoallow
	
	loadmem
	sta	nohud
	
	loadmem
	sta	moredots		
	
;	loadmem
;	sta	colorwarp
	
;	loadmem
;	sta	lsdmode
	
;	loadmem
;	sta	colortrip
	
	loadmem
	sta	randompalette		;56
	
;	loadmem
;	sta	allatonce
	
	loadmem
	sta	randomobjpal
	
;	loadmem
;	sta	colortripobj
	
	loadmem
	sta	gridlines
		
	loadmem
	sta	fpsspeed
	
	loadmem
	sta	currxhair
	
	loadmem
	sta	currxhair2
	
	loadmem
	sta	currxhair3			;64
	
	loadmem
	sta	currxhair4
	
	loadmem
	sta	currxhair5
	
	loadmem
	sta.l	m_wabblemode
	
	loadmem
	sta.l	m_celmode	
	
	loadmem
	sta	curr_ship2
	
	loadmem
	sta	curr_ship3
	
	loadmem
	sta	curr_ship4			;72
	
	loadmem
	sta	curr_ship5
	
	loadmem
	sta	ntscpalswap
	
	loadmem
	sta	noobjmode
	

	rtl
;-----------------------------------------------	

fire_nuke3	; player's special weapon
	s_make_obj		#nuke,.badobj
	s_sprite_obj		y,#0
	s_set_aldata		y,#2,#8
	s_set_alptrs		y,nuke3_Istrat,0,0
	s_set_speed		y,#50
	s_set_lifecnt		y,#28
	s_set_colltype		y,laser
	s_set_colltype		y,friend
	jsl			gen_weapon_l
.badobj	rtl
fire_nuke4	; player's special weapon
	s_make_obj		#nuke,.badobj
	s_sprite_obj		y,#0
	s_set_aldata		y,#2,#8
	s_set_alptrs		y,nuke4_Istrat,0,0
	s_set_speed		y,#50
	s_set_lifecnt		y,#28
	s_set_colltype		y,laser
	s_set_colltype		y,friend
	jsl			gen_weapon_l
.badobj	rtl
fire_nuke5	; player's special weapon
	s_make_obj		#nuke,.badobj
	s_sprite_obj		y,#0
	s_set_aldata		y,#2,#8
	s_set_alptrs		y,nuke5_Istrat,0,0
	s_set_speed		y,#50
	s_set_lifecnt		y,#28
	s_set_colltype		y,laser
	s_set_colltype		y,friend
	jsl			gen_weapon_l
.badobj	rtl
